"use strict";

/**
 * State attribute definitions for all known SENEC data points.
 *
 * Each entry maps a state key to its metadata. Only non-default fields need to be specified.
 *
 * Available fields:
 *   name        (string, required)  — Human-readable name for the state
 *   unit        (string, default "") — Unit of measurement (e.g. "W", "kWh", "%", "°C")
 *   booltype    (boolean, default false) — Value is a boolean (0/1 → false/true)
 *   datetype    (boolean, default false) — Value is a timestamp (seconds or ms → Date string)
 *   iptype      (boolean, default false) — Value is an IP address (decimal → dotted notation)
 *   stringtype  (boolean, default false) — Value must stay as string (skip numeric conversion)
 *   multiply    (number, default 1)  — Multiply raw value by this factor (e.g. 0.01, 0.001)
 */

module.exports = {
	"AMPACE.CELL_TEMPERATURES_MODULE_A": { name: "CELL_TEMPERATURES_MODULE_A", unit: "°C", multiply: 0.1 },
	"AMPACE.CELL_TEMPERATURES_MODULE_B": { name: "CELL_TEMPERATURES_MODULE_B", unit: "°C", multiply: 0.1 },
	"AMPACE.MODULE_ALARM_STATE": { name: "MODULE_ALARM_STATE" },
	"AMPACE.MODULE_FAULT_STATE": { name: "MODULE_FAULT_STATE" },
	"AMPACE.MODULE_MAX_TEMP": { name: "MODULE_MAX_TEMP", unit: "°C", multiply: 0.1 },
	"AMPACE.MODULE_MIN_TEMP": { name: "MODULE_MIN_TEMP", unit: "°C", multiply: 0.1 },
	"AMPACE.MODULE_WARNING_STATE": { name: "MODULE_WARNING_STATE" },
	"AMPACE.PRODUCT_DATE": { name: "PRODUCT_DATE" },
	"AMPACE.PRODUCT_LINE": { name: "PRODUCT_LINE" },
	"AMPACE.RACK_ALARM_STATE": { name: "RACK_ALARM_STATE" },
	"AMPACE.RACK_ALARM_STATE_POS": { name: "RACK_ALARM_STATE_POS" },
	"AMPACE.RACK_FAULT_STATE": { name: "RACK_FAULT_STATE" },
	"AMPACE.RACK_FAULT_STATE_POS": { name: "RACK_FAULT_STATE_POS" },
	"AMPACE.RACK_OFFLINE_STATUS": { name: "RACK_OFFLINE_STATUS" },
	"AMPACE.RACK_RESERVED_DATA": { name: "RACK_RESERVED_DATA" },
	"AMPACE.RACK_WARNING_STATE": { name: "RACK_WARNING_STATE" },
	"AMPACE.RACK_WARNING_STATE_POS": { name: "RACK_WARNING_STATE_POS" },
	AUTARKY_IN_PERCENT: { name: "AUTARKY_IN_PERCENT", unit: "%" },
	"BAT1.BATTERIES_MISSING": { name: "BATTERIES_MISSING" },
	"BAT1.CEI_LIMIT": { name: "CEI_LIMIT" },
	"BAT1.DRM0_ASSERT": { name: "DRM0_ASSERT" },
	"BAT1.ISLAND_ENABLE": { name: "ISLAND_ENABLE", booltype: true },
	"BAT1.NSP2_FW": { name: "NSP2_FW" },
	"BAT1.NSP_FW": { name: "NSP_FW" },
	"BAT1.REQ_HV_UPD": { name: "REQ_HV_UPD" },
	"BAT1.REQ_LV_UPD": { name: "REQ_LV_UPD" },
	"BAT1.RESET": { name: "Bat1 Reset", booltype: true },
	"BAT1.SELFTEST_ACT": { name: "Bat1 Selftest ACT" },
	"BAT1.SELFTEST_LIMIT": { name: "Bat1 Selftest Limit" },
	"BAT1.SELFTEST_OFF": { name: "Bat1 Selftest Off", booltype: true },
	"BAT1.SELFTEST_OVERALL_STATE": { name: "Bat1 Selftest Overall State" },
	"BAT1.SELFTEST_STATE": { name: "Bat1 Selftest State" },
	"BAT1.SELFTEST_STEP": { name: "Bat1 Selftest Step" },
	"BAT1.SELFTEST_TIME": { name: "Bat1 Selftest Time" },
	"BAT1.SERIAL": { name: "Bat1 Serial" },
	"BAT1.SPARE_CAPACITY": { name: "SPARE_CAPACITY" },
	"BAT1.TRIG_ITALY_SELF": { name: "Bat1 Trig Italy Self" },
	"BAT1.TYPE": { name: "TYPE" },
	"BAT1OBJ1.ADR": { name: "ADR" },
	"BAT1OBJ1.BMS_ALARM_STATUS": { name: "BMS_ALARM_STATUS" },
	"BAT1OBJ1.BMS_BATTERY_SOC": { name: "BMS_BATTERY_SOC", unit: "%" },
	"BAT1OBJ1.BMS_BATTERY_STATUS": { name: "BMS_BATTERY_STATUS" },
	"BAT1OBJ1.BMS_MAX_TEMP": { name: "BMS_MAX_TEMP", unit: "°C", multiply: 0.1 },
	"BAT1OBJ1.BMS_MIN_TEMP": { name: "BMS_MIN_TEMP", unit: "°C", multiply: 0.1 },
	"BAT1OBJ1.BMS_NR_ACTIVE": { name: "BMS_NR_ACTIVE" },
	"BAT1OBJ1.BMS_NR_CHARGE": { name: "BMS_NR_CHARGE" },
	"BAT1OBJ1.BMS_NR_DISCHARGE": { name: "BMS_NR_DISCHARGE" },
	"BAT1OBJ1.BMS_NR_INSTALLED": { name: "BMS_NR_INSTALLED" },
	"BAT1OBJ1.BMS_SW_VER": { name: "BMS_SW_VER" },
	"BAT1OBJ1.BMS_SYSTEM_SOC": { name: "BMS_SYSTEM_SOC", unit: "%", multiply: 0.1 },
	"BAT1OBJ1.BMS_TOTAL_CURRENT": { name: "BMS_TOTAL_CURRENT", unit: "A" },
	"BAT1OBJ1.BMS_TOTAL_VOLTAGE": { name: "BMS_TOTAL_VOLTAGE", unit: "V" },
	"BAT1OBJ1.COMM": { name: "COMM" },
	"BAT1OBJ1.ENABLED": { name: "ENABLED", booltype: true },
	"BAT1OBJ1.ERROR": { name: "ERROR" },
	"BAT1OBJ1.INV_CYCLE": { name: "INV_CYCLE" },
	"BAT1OBJ1.I_DC": { name: "I_DC", unit: "A" },
	"BAT1OBJ1.I_DC_MAX": { name: "I_DC_MAX", unit: "A" },
	"BAT1OBJ1.P": { name: "P" },
	"BAT1OBJ1.Q": { name: "Q" },
	"BAT1OBJ1.S": { name: "S" },
	"BAT1OBJ1.SPECIAL_TIMEOUT": { name: "SPECIAL_TIMEOUT" },
	"BAT1OBJ1.STATE": { name: "STATE" },
	"BAT1OBJ1.SW_VERSION": { name: "SW_VERSION" },
	"BAT1OBJ1.SW_VERSION2": { name: "SW_VERSION2" },
	"BAT1OBJ1.SW_VERSION3": { name: "SW_VERSION3" },
	"BAT1OBJ1.TEMP1": { name: "TEMP1", unit: "°C" },
	"BAT1OBJ1.TEMP2": { name: "TEMP2", unit: "°C" },
	"BAT1OBJ1.TEMP3": { name: "TEMP3", unit: "°C" },
	"BAT1OBJ1.TEMP4": { name: "TEMP4", unit: "°C" },
	"BAT1OBJ1.TEMP5": { name: "TEMP5", unit: "°C" },
	"BAT1OBJ1.U_DC": { name: "U_DC", unit: "V" },
	BATTERY_EXPORT: { name: "Battery Discharge", unit: "kWh" },
	BATTERY_IMPORT: { name: "Battery Charge", unit: "kWh" },
	BATTERY_LEVEL_IN_PERCENT: { name: "BATTERY_LEVEL_IN_PERCENT", unit: "%" },
	"BMS.ALARM_STATUS": { name: "ALARM_STATUS" },
	"BMS.ALLOWRECOVER": { name: "ALLOWRECOVER" },
	"BMS.BATTERY_STATUS": { name: "BATTERY_STATUS" },
	"BMS.BL": { name: "BL" },
	"BMS.BMS_READY_FLAG": { name: "BMS Ready Flag", booltype: true },
	"BMS.BMS_STATUS": { name: "BMS Status", booltype: true },
	"BMS.BMS_STATUS_TIMESTAMP": { name: "BMS Status Timestamp", booltype: true },
	"BMS.CELL_BALANCE_STATUS": { name: "CELL_BALANCE_STATUS" },
	"BMS.CELL_TEMPERATURES_MODULE_A": { name: "CELL_TEMPERATURES_MODULE_A", unit: "°C" },
	"BMS.CELL_TEMPERATURES_MODULE_B": { name: "CELL_TEMPERATURES_MODULE_B", unit: "°C" },
	"BMS.CELL_TEMPERATURES_MODULE_C": { name: "CELL_TEMPERATURES_MODULE_C", unit: "°C" },
	"BMS.CELL_TEMPERATURES_MODULE_D": { name: "CELL_TEMPERATURES_MODULE_D", unit: "°C" },
	"BMS.CELL_VOLTAGES_MODULE_A": { name: "CELL_VOLTAGES_MODULE_A", unit: "mV" },
	"BMS.CELL_VOLTAGES_MODULE_B": { name: "CELL_VOLTAGES_MODULE_V", unit: "mV" },
	"BMS.CELL_VOLTAGES_MODULE_C": { name: "CELL_VOLTAGES_MODULE_C", unit: "mV" },
	"BMS.CELL_VOLTAGES_MODULE_D": { name: "CELL_VOLTAGES_MODULE_D", unit: "mV" },
	"BMS.CHARGED_ENERGY": { name: "Charged Energy", unit: "Wh" },
	"BMS.CHARGE_CURRENT_LIMIT": { name: "Charge Current Limit", unit: "A" },
	"BMS.COMMERRCOUNT": { name: "COMMERRCOUNT" },
	"BMS.CURRENT": { name: "Current", unit: "A" },
	"BMS.CYCLES": { name: "Cycles" },
	"BMS.DERATING": { name: "DERATING" },
	"BMS.DISCHARGED_ENERGY": { name: "Discharged Energy", unit: "Wh" },
	"BMS.DISCHARGE_CURRENT_LIMIT": { name: "Discharge current limit", unit: "A" },
	"BMS.ERROR": { name: "BMS Error" },
	"BMS.FAULTLINECOUNT": { name: "FAULTLINECOUNT" },
	"BMS.FW": { name: "FW" },
	"BMS.HW_EXTENSION": { name: "HW Extension" },
	"BMS.HW_MAINBOARD": { name: "HW Mainboard" },
	"BMS.MANUFACTURER": { name: "Manufacturer" },
	"BMS.MAX_CELL_VOLTAGE": { name: "Max Cell Voltage", unit: "V", multiply: 0.01 },
	"BMS.MAX_TEMP": { name: "MAX_TEMP", unit: "°C", multiply: 0.1 },
	"BMS.MIN_CELL_VOLTAGE": { name: "Min Cell Voltage", unit: "V", multiply: 0.01 },
	"BMS.MIN_TEMP": { name: "MIN_TEMP", unit: "°C", multiply: 0.1 },
	"BMS.MODULES_CONFIGURED": { name: "# Modules Configured" },
	"BMS.MODULE_COUNT": { name: "# Modules" },
	"BMS.NOM_CHARGEPOWER_MODULE": { name: "Nominal Chargepower Module", unit: "W" },
	"BMS.NOM_DISCHARGEPOWER_MODULE": { name: "Nominal Dischargepower Module", unit: "W" },
	"BMS.NR_ACTIVE": { name: "NR_ACTIVE" },
	"BMS.NR_CHARGE": { name: "NR_CHARGE" },
	"BMS.NR_DISCHARGE": { name: "NR_DISCHARGE" },
	"BMS.NR_INSTALLED": { name: "NR_INSTALLED" },
	"BMS.PROTOCOL": { name: "PROTOCOL" },
	"BMS.RECOVERLOCKED": { name: "BMS Recover Locked", booltype: true },
	"BMS.SERIAL": { name: "BMS Serial" },
	"BMS.SN": { name: "SN" },
	"BMS.SOC": { name: "SOC", unit: "%" },
	"BMS.SOH": { name: "SOH", unit: "%" },
	"BMS.START_RL_TST": { name: "START_RL_TST" },
	"BMS.START_SELFTEST": { name: "BMS Start Selftest", booltype: true },
	"BMS.START_UPDATE": { name: "Start Update", booltype: true },
	"BMS.STATUS": { name: "Status", booltype: true },
	"BMS.SYSTEM_CHARGE_CURRENT_LIMIT": { name: "SYSTEM_CHARGE_CURRENT_LIMIT" },
	"BMS.SYSTEM_DISCHARGE_CURRENT_LIMIT": { name: "SYSTEM_DISCHARGE_CURRENT_LIMIT" },
	"BMS.SYSTEM_SOC": { name: "SYSTEM_SOC", unit: "%", multiply: 0.1 },
	"BMS.SYSTEM_SOH": { name: "SYSTEM_SOH", unit: "%", multiply: 0.1 },
	"BMS.TEMP_MAX": { name: "Temp Max", unit: "°C" },
	"BMS.TEMP_MIN": { name: "Temp Min", unit: "°C" },
	"BMS.TF_ERROR": { name: "TF Error", booltype: true },
	"BMS.TOTAL_CURRENT": { name: "TOTAL_CURRENT", unit: "A" },
	"BMS.TOTAL_VOLTAGE": { name: "TOTAL_VOLTAGE", unit: "V" },
	"BMS.VOLTAGE": { name: "Voltage", unit: "V" },
	"BMS.WIZARD_ABORT": { name: "Wizard Abort", booltype: true },
	"BMS.WIZARD_CONFDETECTION": { name: "WIZARD_CONFDETECTION", booltype: true },
	"BMS.WIZARD_CONFIRM": { name: "Wizard Confirm", booltype: true },
	"BMS.WIZARD_DCCONNECT": { name: "Wizard DC Connect", booltype: true },
	"BMS.WIZARD_FINISHEDDETECTION": { name: "WIZARD_FINISHEDDETECTION", booltype: true },
	"BMS.WIZARD_RESDETECTION": { name: "WIZARD_RESDETECTION", booltype: true },
	"BMS.WIZARD_RS485ISO_INSTALLED": { name: "WIZARD_RS485ISO_INSTALLED", booltype: true },
	"BMS.WIZARD_START": { name: "Wizard Start", booltype: true },
	"BMS.WIZARD_STARTDETECTION": { name: "WIZARD_STARTDETECTION", booltype: true },
	"BMS.WIZARD_STATE": { name: "Wizard State" },
	"BMS.WIZARD_TIMEOUTDETECTION": { name: "WIZARD_TIMEOUTDETECTION", booltype: true },
	"BMS.WIZARD_VAL_STATUS": { name: "WIZARD_VAL_STATUS" },
	"BMS_PARA.FORCE_BMS_ERROR": { name: "FORCE_BMS_ERROR", booltype: true },
	"BMS_PARA.FORCE_OP_MODE": { name: "FORCE_OP_MODE", booltype: true },
	"BMS_PARA.FULL_CELL_VOLTAGE_MV": { name: "FULL_CELL_VOLTAGE_MV", unit: "mV" },
	"BMS_PARA.MAX_MODULE_CHARGE_CURRENT_LIMIT_A": { name: "MAX_MODULE_CHARGE_CURRENT_LIMIT_A", unit: "A" },
	"BMS_PARA.MAX_MODULE_DISCHARGE_CURRENT_LIMIT_A": { name: "MAX_MODULE_DISCHARGE_CURRENT_LIMIT_A", unit: "A" },
	"BMS_PARA.OPERATIONAL_MODE": { name: "OPERATIONAL_MODE" },
	"BMS_PARA.USE_ROA_PARAMETER": { name: "USE_ROA_PARAMETER", booltype: true },
	"BMZ_CURRENT_LIMITS.MAX_CURRENT_LIMIT_A": { name: "MAX_CURRENT_LIMIT_A", unit: "A" },
	"BMZ_CURRENT_LIMITS.MIN_CURRENT_LIMIT_A": { name: "MIN_CURRENT_LIMIT_A", unit: "A" },
	"CASC.BATPOWERSUM": { name: "Battery power sum", unit: "W" },
	"CASC.POWER": { name: "Power", unit: "W" },
	"CASC.POWER0": { name: "CASC.POWER0", unit: "W" },
	"CASC.POWER1": { name: "CASC.POWER1", unit: "W" },
	"CASC.POWER2": { name: "CASC.POWER2", unit: "W" },
	"CASC.POWER3": { name: "CASC.POWER3", unit: "W" },
	"CASC.POWER4": { name: "CASC.POWER4", unit: "W" },
	"CASC.POWER5": { name: "CASC.POWER5", unit: "W" },
	"CASC.PVGEN": { name: "PV generation", unit: "W" },
	"CASC.PVMASTER": { name: "PV master" },
	"CASC.SOC": { name: "SOC (State of charge)", unit: "%" },
	"CASC.SOC0": { name: "CASC.SOC0", unit: "%" },
	"CASC.SOC1": { name: "CASC.SOC1", unit: "%" },
	"CASC.SOC2": { name: "CASC.SOC2", unit: "%" },
	"CASC.SOC3": { name: "CASC.SOC3", unit: "%" },
	"CASC.SOC4": { name: "CASC.SOC4", unit: "%" },
	"CASC.SOC5": { name: "CASC.SOC5", unit: "%" },
	"CASC.STATE": { name: "State" },
	"CASC.STATE0": { name: "CASC.STATE0" },
	"CASC.STATE1": { name: "CASC.STATE1" },
	"CASC.STATE2": { name: "CASC.STATE2" },
	"CASC.STATE3": { name: "CASC.STATE3" },
	"CASC.STATE4": { name: "CASC.STATE4" },
	"CASC.STATE5": { name: "CASC.STATE5" },
	"CASC.TARGET": { name: "Target" },
	"CASC.TARGET0": { name: "CASC.TARGET0" },
	"CASC.TARGET1": { name: "CASC.TARGET1" },
	"CASC.TARGET2": { name: "CASC.TARGET2" },
	"CASC.TARGET3": { name: "CASC.TARGET3" },
	"CASC.TARGET4": { name: "CASC.TARGET4" },
	"CASC.TARGET5": { name: "CASC.TARGET5" },
	"CELL_DEVIATION_ROC.SKIP_WAITING": { name: "SKIP_WAITING", booltype: true },
	"CURRENT_IMBALANCE_CONTROL.THRESHOLD_mA": { name: "THRESHOLD_mA", unit: "mA" },
	"DEBUG.CHARGE_TARGET": { name: "DEBUG.CHARGE_TARGET" },
	"DEBUG.DC_TARGET": { name: "DC_TARGET" },
	"DEBUG.DC_TARGET_PID_KD": { name: "DC_TARGET_PID_KD" },
	"DEBUG.DC_TARGET_PID_KI": { name: "DC_TARGET_PID_KI" },
	"DEBUG.DC_TARGET_PID_KP": { name: "DC_TARGET_PID_KP" },
	"DEBUG.EG_POT_BOOST_CAP": { name: "EG_POT_BOOST_CAP" },
	"DEBUG.EG_POT_BOOST_POW": { name: "EG_POT_BOOST_POW" },
	"DEBUG.EG_POT_CHARGE_CAP": { name: "EG_POT_CHARGE_CAP", unit: "Wh" },
	"DEBUG.EG_POT_CHARGE_POW": { name: "EG_POT_CHARGE_POW", unit: "W" },
	"DEBUG.EX_DUMP": { name: "EX_DUMP" },
	"DEBUG.EX_DUMP_FILE": { name: "EX_DUMP_FILE" },
	"DEBUG.FEED_TARGET": { name: "FEED_TARGET" },
	"DEBUG.INFO_DUMP": { name: "INFO_DUMP", booltype: true },
	"DEBUG.PU_AVAIL": { name: "PU_AVAIL", booltype: true },
	"DEBUG.RAM_DUMP": { name: "RAM_DUMP", booltype: true },
	"DEBUG.SECTIONS": { name: "Sections" },
	"DEBUG.STACK_MONITOR": { name: "STACK_MONITOR", booltype: true },
	"EG_CONTROL.ACTIVE": { name: "ACTIVE", booltype: true },
	"EG_CONTROL.EG_MTR_ERROR": { name: "EG_MTR_ERROR" },
	"EG_CONTROL.EG_SW_ERROR": { name: "EG_SW_ERROR" },
	"EG_CONTROL.ERROR_EG_METER": { name: "ERROR_EG_METER" },
	"EG_CONTROL.ERROR_EG_SWITCH": { name: "ERROR_EG_SWITCH" },
	"EG_CONTROL.POWER_METER_INFO_RES": { name: "POWER_METER_INFO_RES" },
	"EG_CONTROL.POWER_METER_INFO_TRIG": { name: "POWER_METER_INFO_TRIG" },
	"EG_CONTROL.POWER_METER_SERIAL": { name: "POWER_METER_SERIAL" },
	"EG_CONTROL.TEST_EG_METER_RES": { name: "TEST_EG_METER_RES" },
	"EG_CONTROL.TEST_EG_METER_TRIG": { name: "TEST_EG_METER_TRIG" },
	"EG_CONTROL.TEST_EG_SWITCH_RES": { name: "TEST_EG_SWITCH_RES" },
	"EG_CONTROL.TEST_EG_SWITCH_TRIG": { name: "TEST_EG_SWITCH_TRIG" },
	"ENERGY.CAPTESTMODULE": { name: "Capacity Test Module", booltype: true },
	"ENERGY.FORCE_FULL_CHARGE": { name: "Force Full Charge", booltype: true },
	"ENERGY.GRID_POWER_OFFSET": { name: "GRID_POWER_OFFSET" },
	"ENERGY.GUI_BAT_DATA_CAPACITY": { name: "GUI_BAT_DATA_CAPACITY" },
	"ENERGY.GUI_BAT_DATA_COLLECTED": { name: "GUI_BAT_DATA_COLLECTED", booltype: true },
	"ENERGY.GUI_BAT_DATA_CURRENT": { name: "Battery Current", unit: "A" },
	"ENERGY.GUI_BAT_DATA_FUEL_CHARGE": { name: "Accu Level", unit: "%" },
	"ENERGY.GUI_BAT_DATA_MAX_CELL_VOLTAGE": { name: "BAT_DATA_MAX_CELL_VOLTAGE", unit: "mV" },
	"ENERGY.GUI_BAT_DATA_MIN_CELL_VOLTAGE": { name: "BAT_DATA_MIN_CELL_VOLTAGE", unit: "mV" },
	"ENERGY.GUI_BAT_DATA_OA_CHARGING": { name: "BAT_DATA_OA_CHARGING", unit: "W" },
	"ENERGY.GUI_BAT_DATA_OA_ENERGY": { name: "GUI_BAT_DATA_OA_ENERGY" },
	"ENERGY.GUI_BAT_DATA_POWER": { name: "Accu Power current", unit: "W" },
	"ENERGY.GUI_BAT_DATA_VOLTAGE": { name: "Battery Voltage", unit: "V" },
	"ENERGY.GUI_BOOSTING_INFO": { name: "Boost", booltype: true },
	"ENERGY.GUI_CAP_TEST_DIS_COUNT": { name: "CAP_TEST_DIS_COUNT" },
	"ENERGY.GUI_CAP_TEST_START": { name: "GUI_CAP_TEST_START", booltype: true },
	"ENERGY.GUI_CAP_TEST_STATE": { name: "GUI_CAP_TEST_STATE" },
	"ENERGY.GUI_CAP_TEST_STOP": { name: "GUI_CAP_TEST_STOP", booltype: true },
	"ENERGY.GUI_CHARGING_INFO": { name: "Accu charging", booltype: true },
	"ENERGY.GUI_EQUAL_CHARGE_RUN": { name: "GUI_EQUAL_CHARGE_RUN", booltype: true },
	"ENERGY.GUI_EQUAL_CHARGE_START": { name: "GUI_EQUAL_CHARGE_START", booltype: true },
	"ENERGY.GUI_EQUAL_CHARGE_STOP": { name: "GUI_EQUAL_CHARGE_STOP", booltype: true },
	"ENERGY.GUI_FACTORY_TEST_FAN": { name: "GUI_FACTORY_TEST_FAN", booltype: true },
	"ENERGY.GUI_FACTORY_TEST_PUMP": { name: "GUI_FACTORY_TEST_PUMP", booltype: true },
	"ENERGY.GUI_FACTORY_TEST_RELAY": { name: "GUI_FACTORY_TEST_RELAY", booltype: true },
	"ENERGY.GUI_FACTORY_TEST_XCOM": { name: "GUI_FACTORY_TEST_XCOM", booltype: true },
	"ENERGY.GUI_GRID_POW": { name: "Net Power Current", unit: "W" },
	"ENERGY.GUI_HOUSE_POW": { name: "House Power Current", unit: "W" },
	"ENERGY.GUI_INIT_CHARGE_START": { name: "GUI_INIT_CHARGE_START", booltype: true },
	"ENERGY.GUI_INIT_CHARGE_STOP": { name: "GUI_INIT_CHARGE_START", booltype: true },
	"ENERGY.GUI_INVERTER_POWER": { name: "PV Power current", unit: "W" },
	"ENERGY.GUI_MAINT_CHARGE_START": { name: "GUI_MAINT_CHARGE_START", booltype: true },
	"ENERGY.GUI_MAINT_CHARGE_STOP": { name: "GUI_MAINT_CHARGE_STOP", booltype: true },
	"ENERGY.GUI_PAUSE_SPECIAL": { name: "GUI_PAUSE_SPECIAL", booltype: true },
	"ENERGY.GUI_SAFETY_CHARGE": { name: "Safety Charge active", booltype: true },
	"ENERGY.GUI_SCHARGE_ELAPSED": { name: "GUI_SCHARGE_ELAPSED" },
	"ENERGY.GUI_SCHARGE_REMAIN": { name: "GUI_SCHARGE_REMAIN" },
	"ENERGY.GUI_SULFAT_CHARGE_START": { name: "GUI_SULFAT_CHARGE_START", booltype: true },
	"ENERGY.GUI_SULFAT_CHARGE_STOP": { name: "GUI_SULFAT_CHARGE_STOP", booltype: true },
	"ENERGY.GUI_TEST_CHARGE_STAT": { name: "GUI_TEST_CHARGE_STAT", booltype: true },
	"ENERGY.GUI_TEST_DISCHARGE_STAT": { name: "GUI_TEST_DISCHARGE_STAT", booltype: true },
	"ENERGY.INIT_CHARGE_ACK": { name: "INIT_CHARGE_ACK", booltype: true },
	"ENERGY.INIT_CHARGE_DIFF_VOLTAGE": { name: "INIT_CHARGE_DIFF_VOLTAGE", unit: "V" },
	"ENERGY.INIT_CHARGE_MAX_CURRENT": { name: "INIT_CHARGE_MAX_CURRENT", unit: "W" },
	"ENERGY.INIT_CHARGE_MAX_VOLTAGE": { name: "INIT_CHARGE_MAX_VOLTAGE", unit: "V" },
	"ENERGY.INIT_CHARGE_MIN_VOLTAGE": { name: "INIT_CHARGE_MIN_VOLTAGE", unit: "V" },
	"ENERGY.INIT_CHARGE_RERUN": { name: "INIT_CHARGE_RERUN", booltype: true },
	"ENERGY.INIT_CHARGE_RUNNING": { name: "INIT_CHARGE_RUNNING", booltype: true },
	"ENERGY.INIT_CHARGE_STATE": { name: "INIT_CHARGE_STATE" },
	"ENERGY.INIT_CHARGE_TIMER": { name: "INIT_CHARGE_TIMER" },
	"ENERGY.INIT_CHARGE_WATER_READY": { name: "INIT_CHARGE_WATER_READY", booltype: true },
	"ENERGY.INIT_DISCHARGE_MAX_CURRENT": { name: "INIT_DISCHARGE_MAX_CURRENT", unit: "A" },
	"ENERGY.LI_STORAGE_MODE_RUNNING": { name: "LI_STORAGE_MODE_RUNNING", booltype: true },
	"ENERGY.LI_STORAGE_MODE_START": { name: "LI_STORAGE_MODE_START", booltype: true },
	"ENERGY.LI_STORAGE_MODE_STOP": { name: "LI_STORAGE_MODE_STOP", booltype: true },
	"ENERGY.MAINT_CHARGE_FINISHED": { name: "MAINT_CHARGE_FINISHED", booltype: true },
	"ENERGY.MAINT_CHARGE_INTERVAL": { name: "MAINT_CHARGE_INTERVAL" },
	"ENERGY.MAINT_CHARGE_READY": { name: "MAINT_CHARGE_READY", booltype: true },
	"ENERGY.MAINT_CHARGE_RUNNING": { name: "MAINT_CHARGE_RUNNING", booltype: true },
	"ENERGY.OFFPEAK_CURRENT": { name: "Offpeak Current", unit: "A" },
	"ENERGY.OFFPEAK_DURATION": { name: "Offpeak Duration" },
	"ENERGY.OFFPEAK_POWER": { name: "Offpeak Power", unit: "W" },
	"ENERGY.OFFPEAK_RUNNING": { name: "Offpeak Running", booltype: true },
	"ENERGY.OFFPEAK_TARGET": { name: "Offpeak Target" },
	"ENERGY.SAFE_CHARGE_FORCE": { name: "Safety charge forced", booltype: true },
	"ENERGY.SAFE_CHARGE_PROHIBIT": { name: "Safety charge prohibited", booltype: true },
	"ENERGY.SAFE_CHARGE_RUNNING": { name: "Safety charge running", booltype: true },
	"ENERGY.STAT_DAYS_SINCE_MAINT": { name: "Days since maintenance", unit: "d" },
	"ENERGY.STAT_HOURS_OF_OPERATION": { name: "Hours of operation", unit: "h" },
	"ENERGY.STAT_LIMITED_NET_SKEW": { name: "LIMITED_NET_SKEW", booltype: true },
	"ENERGY.STAT_LIMITED_NO_STAND_BY": { name: "LIMITED_NO_STAND_BY", booltype: true },
	"ENERGY.STAT_LIMITED_RCR": { name: "STAT_LIMITED_RCR", booltype: true },
	"ENERGY.STAT_MAINT_REQUIRED": { name: "Maintenance required", booltype: true },
	"ENERGY.STAT_STATE": { name: "System Mode" },
	"ENERGY.STAT_STATE_DECODE": { name: "System Mode decode" },
	"ENERGY.STAT_STATE_Text": { name: "System Mode" },
	"ENERGY.STAT_SULFAT_CHRG_COUNTER": { name: "SULFAT_CHRG_COUNTER" },
	"ENERGY.SULFAT_CHARGE_RUN": { name: "SULFAT_CHARGE_RUN", booltype: true },
	"ENERGY.SUPP_BATT_DIAG": { name: "SUPP_BATT_DIAG", booltype: true },
	"ENERGY.TEST_CHARGE_CHRG_START": { name: "TEST_CHARGE_CHRG_START", booltype: true },
	"ENERGY.TEST_CHARGE_CHRG_STOP": { name: "TEST_CHARGE_CHRG_STOP", booltype: true },
	"ENERGY.TEST_CHARGE_DIS_START": { name: "TEST_CHARGE_DIS_START", booltype: true },
	"ENERGY.TEST_CHARGE_DIS_STOP": { name: "TEST_CHARGE_DIS_STOP", booltype: true },
	"ENERGY.TEST_CYCLE": { name: "TEST_CYCLE", booltype: true },
	"ENERGY.VPP_ACTIVATE_EXPORT_LIMIT": { name: "VPP_ACTIVATE_EXPORT_LIMIT", booltype: true },
	"ENERGY.VPP_ACTIVATE_TARGET_POWER": { name: "VPP_ACTIVATE_TARGET_POWER" },
	"ENERGY.VPP_DAILY_PARAMETER_RESET": { name: "VPP_DAILY_PARAMETER_RESET" },
	"ENERGY.VPP_ENDTIME_HOUR": { name: "VPP_ENDTIME_HOUR" },
	"ENERGY.VPP_ENDTIME_MINUTE": { name: "VPP_ENDTIME_MINUTE" },
	"ENERGY.VPP_EXPORT_LIMIT": { name: "VPP_EXPORT_LIMIT" },
	"ENERGY.VPP_IGNORE_COUNTRY_TYPE": { name: "VPP_IGNORE_COUNTRY_TYPE", booltype: true },
	"ENERGY.VPP_IS_ACTIVE": { name: "VPP_IS_ACTIVE", booltype: true },
	"ENERGY.VPP_LAST_CHANGE_UTC": { name: "VPP_LAST_CHANGE_UTC" },
	"ENERGY.VPP_STARTTIME_HOUR": { name: "VPP_STARTTIME_HOUR" },
	"ENERGY.VPP_STARTTIME_MINUTE": { name: "VPP_STARTTIME_MINUTE" },
	"ENERGY.VPP_TARGET_POWER": { name: "VPP_TARGET_POWER", unit: "W" },
	"ENERGY.ZERO_EXPORT": { name: "ZERO_EXPORT", booltype: true },
	"FACTORY.AUX_TYPE": { name: "AUX_TYPE" },
	"FACTORY.BAT_TYPE": { name: "BAT_TYPE" },
	"FACTORY.BAT_TYPE_Text": { name: "BAT_TYPE" },
	"FACTORY.BEH_FLAGS": { name: "BEH_FLAGS" },
	"FACTORY.CELL_TYPE": { name: "CELL_TYPE" },
	"FACTORY.COUNTRY": { name: "COUNTRY" },
	"FACTORY.COUNTRY_Text": { name: "COUNTRY" },
	"FACTORY.DESIGN_CAPACITY": { name: "Design capactiy", unit: "kWh", multiply: 0.001 },
	"FACTORY.DEVICE_ID": { name: "Device ID", stringtype: true },
	"FACTORY.EPA_GRID_FILTER": { name: "EPA_GRID_FILTER" },
	"FACTORY.FAC_SANITY": { name: "FAC_SANITY" },
	"FACTORY.MAX_CHARGE_POWER_DC": { name: "maximum charge power DC", unit: "W" },
	"FACTORY.MAX_DISCHARGE_POWER_DC": { name: "maximum discharge power DC", unit: "W" },
	"FACTORY.PM_TYPE": { name: "PM_TYPE" },
	"FACTORY.SYS_TYPE": { name: "System Type" },
	"FACTORY.SYS_TYPE_Text": { name: "System Type" },
	"FACTORY.TEMP_TYPE": { name: "TEMP_TYPE" },
	"FAN_SPEED.INV_HV": { name: "INV_HV" },
	"FAN_SPEED.INV_LV": { name: "INV_LV" },
	"FAN_TEST.INV_HV": { name: "INV_HV" },
	"FAN_TEST.INV_LV": { name: "INV_LV" },
	"FEATURES.CAR": { name: "Car", booltype: true },
	"FEATURES.CLOUDREADY": { name: "Cloud Ready", booltype: true },
	"FEATURES.ECOGRIDREADY": { name: "Econamic Grid Ready", booltype: true },
	"FEATURES.HEAT": { name: "Heat", booltype: true },
	"FEATURES.ISLAND": { name: "Island", booltype: true },
	"FEATURES.ISLAND_PRO": { name: "ISLAND_PRO", booltype: true },
	"FEATURES.PEAKSHAVING": { name: "Peakshaving", booltype: true },
	"FEATURES.SGREADY": { name: "SG Ready", booltype: true },
	"FEATURES.SHKW": { name: "SHKW", booltype: true },
	"FEATURES.SOCKETS": { name: "Sockets", booltype: true },
	"GRIDCONFIG.AU2020_ACTIVE_REGISTER": { name: "AU2020_ACTIVE_REGISTER" },
	"GRIDCONFIG.AU2020_COSPHIMODE": { name: "AU2020_COSPHIMODE" },
	"GRIDCONFIG.AU2020_FIXEDFACTOR": { name: "AU2020_FIXEDFACTOR" },
	"GRIDCONFIG.AU2020_FLLCO": { name: "AU2020_FLLCO" },
	"GRIDCONFIG.AU2020_FLLCO_MAX": { name: "AU2020_FLLCO_MAX" },
	"GRIDCONFIG.AU2020_FLLCO_MIN": { name: "AU2020_FLLCO_MIN" },
	"GRIDCONFIG.AU2020_FPMAX": { name: "AU2020_FPMAX" },
	"GRIDCONFIG.AU2020_FPMAX_MAX": { name: "AU2020_FPMAX_MAX" },
	"GRIDCONFIG.AU2020_FPMAX_MIN": { name: "AU2020_FPMAX_MIN" },
	"GRIDCONFIG.AU2020_FPMIN": { name: "AU2020_FPMIN" },
	"GRIDCONFIG.AU2020_FPMIN_MAX": { name: "AU2020_FPMIN_MAX" },
	"GRIDCONFIG.AU2020_FPMIN_MIN": { name: "AU2020_FPMIN_MIN" },
	"GRIDCONFIG.AU2020_FSTOPCH": { name: "AU2020_FSTOPCH" },
	"GRIDCONFIG.AU2020_FSTOPCH_MAX": { name: "AU2020_FSTOPCH_MAX" },
	"GRIDCONFIG.AU2020_FSTOPCH_MIN": { name: "AU2020_FSTOPCH_MIN" },
	"GRIDCONFIG.AU2020_FTRANSITION": { name: "AU2020_FTRANSITION" },
	"GRIDCONFIG.AU2020_FTRANSITION_MAX": { name: "AU2020_FTRANSITION_MAX" },
	"GRIDCONFIG.AU2020_FTRANSITION_MIN": { name: "AU2020_FTRANSITION_MIN" },
	"GRIDCONFIG.AU2020_FULCO": { name: "AU2020_FULCO" },
	"GRIDCONFIG.AU2020_FULCO_MAX": { name: "AU2020_FULCO_MAX" },
	"GRIDCONFIG.AU2020_FULCO_MIN": { name: "AU2020_FULCO_MIN" },
	"GRIDCONFIG.AU2020_HEXPORT": { name: "AU2020_HEXPORT" },
	"GRIDCONFIG.AU2020_HEXPORT_ENABLED": { name: "AU2020_HEXPORT_ENABLED", booltype: true },
	"GRIDCONFIG.AU2020_NOT_DEFAULT": { name: "AU2020_NOT_DEFAULT", booltype: true },
	"GRIDCONFIG.AU2020_REACTIVEPOWER": { name: "AU2020_REACTIVEPOWER", unit: "W" },
	"GRIDCONFIG.AU2020_REACTIVEPOWER_MAX": { name: "AU2020_REACTIVEPOWER_MAX", unit: "W" },
	"GRIDCONFIG.AU2020_REACTIVEPOWER_MIN": { name: "AU2020_REACTIVEPOWER_MIN", unit: "W" },
	"GRIDCONFIG.AU2020_RESPONSE_MODES": { name: "AU2020_RESPONSE_MODES" },
	"GRIDCONFIG.AU2020_SELECTED_REGION": { name: "AU2020_SELECTED_REGION" },
	"GRIDCONFIG.AU2020_VNOMMAX_MAX": { name: "AU2020_VNOMMAX_MAX" },
	"GRIDCONFIG.AU2020_VNOMMAX_MIN": { name: "AU2020_VNOMMAX_MIN" },
	"GRIDCONFIG.AU2020_VNOMMAX_RANGE": { name: "AU2020_VNOMMAX_RANGE" },
	"GRIDCONFIG.AU2020_VVAR_PERCENT": { name: "GRIDCONFIG.AU2020_VVAR_PERCENT" },
	"GRIDCONFIG.AU2020_VVAR_PMAX": { name: "GRIDCONFIG.AU2020_VVAR_PMAX" },
	"GRIDCONFIG.AU2020_VVAR_PMIN": { name: "GRIDCONFIG.AU2020_VVAR_PMIN" },
	"GRIDCONFIG.AU2020_VVAR_VMAX": { name: "GRIDCONFIG.AU2020_VVAR_VMAX" },
	"GRIDCONFIG.AU2020_VVAR_VMIN": { name: "GRIDCONFIG.AU2020_VVAR_VMIN" },
	"GRIDCONFIG.AU2020_VVAR_VOLTAGE": { name: "GRIDCONFIG.AU2020_VVAR_VOLTAGE" },
	"GRIDCONFIG.AU2020_VWC_PERCENT": { name: "GRIDCONFIG.AU2020_VWC_PERCENT" },
	"GRIDCONFIG.AU2020_VWC_PMAX": { name: "GRIDCONFIG.AU2020_VWC_PMAX" },
	"GRIDCONFIG.AU2020_VWC_PMIN": { name: "GRIDCONFIG.AU2020_VWC_PMIN" },
	"GRIDCONFIG.AU2020_VWC_VMAX": { name: "GRIDCONFIG.AU2020_VWC_VMAX" },
	"GRIDCONFIG.AU2020_VWC_VMIN": { name: "GRIDCONFIG.AU2020_VWC_VMIN" },
	"GRIDCONFIG.AU2020_VWC_VOLTAGE": { name: "GRIDCONFIG.AU2020_VWC_VOLTAGE" },
	"GRIDCONFIG.AU2020_VWD_PERCENT": { name: "GRIDCONFIG.AU2020_VWD_PERCENT" },
	"GRIDCONFIG.AU2020_VWD_PMAX": { name: "GRIDCONFIG.AU2020_VWD_PMAX" },
	"GRIDCONFIG.AU2020_VWD_PMIN": { name: "GRIDCONFIG.AU2020_VWD_PMIN" },
	"GRIDCONFIG.AU2020_VWD_VMAX": { name: "GRIDCONFIG.AU2020_VWD_VMAX" },
	"GRIDCONFIG.AU2020_VWD_VMIN": { name: "GRIDCONFIG.AU2020_VWD_VMIN" },
	"GRIDCONFIG.AU2020_VWD_VOLTAGE": { name: "GRIDCONFIG.AU2020_VWD_VOLTAGE" },
	"GRIDCONFIG.AU2020_WGRA": { name: "GRIDCONFIG.AU2020_WGRA" },
	"GRIDCONFIG.AU2020_WGRA_MAX": { name: "GRIDCONFIG.AU2020_WGRA_MAX" },
	"GRIDCONFIG.AU2020_WGRA_MIN": { name: "GRIDCONFIG.AU2020_WGRA_MIN" },
	"GRIDCONFIG.AU_FIXED_FAC": { name: "AU_FIXED_FAC" },
	"GRIDCONFIG.AU_GRID_CODE": { name: "AU_GRID_CODE" },
	"GRIDCONFIG.AU_P_RAMP_CH": { name: "AU_P_RAMP_CH" },
	"GRIDCONFIG.AU_P_RAMP_DI": { name: "AU_P_RAMP_DI" },
	"GRIDCONFIG.AU_RESP_MODE": { name: "AU_RESP_MODE" },
	"GRIDCONFIG.AU_SOFT_RAMP_EN": { name: "AU_SOFT_RAMP_EN" },
	"GRIDCONFIG.AU_TARGET_TY": { name: "AU_TARGET_TY" },
	"GRIDCONFIG.AU_VRR_MAX": { name: "AU_VRR_MAX" },
	"GRIDCONFIG.AU_VRR_MIN": { name: "AU_VRR_MIN" },
	"GRIDCONFIG.AU_VVAR_PERCENTAGE": { name: "AU_VVAR_PERCENTAGE" },
	"GRIDCONFIG.AU_VVAR_P_MAX": { name: "AU_VVAR_P_MAX", unit: "W" },
	"GRIDCONFIG.AU_VVAR_P_MIN": { name: "AU_VVAR_P_MIN", unit: "W" },
	"GRIDCONFIG.AU_VVAR_VOLTAGE": { name: "AU_VVAR_VOLTAGE", unit: "V" },
	"GRIDCONFIG.AU_VWC_VOLTAGE": { name: "AU_VWC_VOLTAGE", unit: "V" },
	"GRIDCONFIG.AU_VWD_VOLTAGE": { name: "AU_VWD_VOLTAGE", unit: "V" },
	"GRIDCONFIG.CEI_COS_PHI": { name: "CEI_COS_PHI" },
	"GRIDCONFIG.CEI_COS_PHI_ENABLE": { name: "CEI_COS_PHI_ENABLE", booltype: true },
	"GRIDCONFIG.CEI_CPHI_LOIN": { name: "CEI_CPHI_LOIN" },
	"GRIDCONFIG.CEI_CPHI_LOUT": { name: "CEI_CPHI_LOUT" },
	"GRIDCONFIG.CEI_FREQ_MAX": { name: "CEI_FREQ_MAX" },
	"GRIDCONFIG.CEI_FREQ_MIN": { name: "CEI_FREQ_MIN" },
	"GRIDCONFIG.CEI_REC_TIME": { name: "CEI_REC_TIME" },
	"GRIDCONFIG.CEI_RED_DROP": { name: "CEI_RED_DROP" },
	"GRIDCONFIG.CEI_SEGNALE_ESTERNO": { name: "CEI_SEGNALE_ESTERNO" },
	"GRIDCONFIG.CEI_STAB_AC_DE": { name: "CEI_STAB_AC_DE" },
	"GRIDCONFIG.CEI_STAB_LO_CO": { name: "CEI_STAB_LO_CO" },
	"GRIDCONFIG.CEI_STAB_LO_TH": { name: "CEI_STAB_LO_TH" },
	"GRIDCONFIG.CEI_STAB_UP_CO": { name: "CEI_STAB_UP_CO" },
	"GRIDCONFIG.CEI_STAB_UP_TH": { name: "CEI_STAB_UP_TH" },
	"GRIDCONFIG.CEI_STAB_VOL_TH": { name: "CEI_STAB_VOL_TH" },
	"GRIDCONFIG.PWRCFG_COS_POINT1": { name: "PWRCFG_COS_POINT1" },
	"GRIDCONFIG.PWRCFG_COS_POINT3": { name: "PWRCFG_COS_POINT3" },
	"GRIDCONFIG.PWRCFG_COS_POINT_2A": { name: "PWRCFG_COS_POINT_2A" },
	"GRIDCONFIG.PWRCFG_COS_POINT_2B": { name: "PWRCFG_COS_POINT_2B" },
	"GRIDCONFIG.PWRCFG_USE_COS_PHI_CURVE": { name: "PWRCFG_USE_COS_PHI_CURVE" },
	"GRIDCONFIG.PWRCFG_USE_MAX_PWR_SKEW": { name: "PWRCFG_USE_MAX_PWR_SKEW" },
	"GRIDCONFIG.VDECOSPHITIME": { name: "VDECOSPHITIME" },
	"GRIDCONFIG.VDEFIXEDFAC": { name: "VDEFIXEDFAC" },
	"GRIDCONFIG.VDEOVERFREQDROOP": { name: "VDEOVERFREQDROOP" },
	"GRIDCONFIG.VDEOVERFREQLIMIT": { name: "VDEOVERFREQLIMIT", unit: "Hz" },
	"GRIDCONFIG.VDEPT1RESPONSETIME": { name: "VDEPT1RESPONSETIME" },
	"GRIDCONFIG.VDERECOVERTIME": { name: "VDERECOVERTIME", unit: "s" },
	"GRIDCONFIG.VDETARGETTY": { name: "VDETARGETTY" },
	"GRIDCONFIG.VDEUNDERFREQDROOP": { name: "VDEUNDERFREQDROOP" },
	"GRIDCONFIG.VDEURMSMAX10": { name: "VDEURMSMAX10" },
	"GRIDCONFIG.VDE_FREQDROPPROT": { name: "VDE_FREQDROPPROT", unit: "Hz" },
	"GRIDCONFIG.VDE_FREQDROPPROTDELAY": { name: "VDE_FREQDROPPROTDELAY", unit: "s" },
	"GRIDCONFIG.VDE_FREQRISEPROT": { name: "VDE_FREQRISEPROT", unit: "Hz" },
	"GRIDCONFIG.VDE_FREQRISEPROTDELAY": { name: "VDE_FREQRISEPROTDELAY", unit: "s" },
	"GRIDCONFIG.VDE_UNDERFREQLIMIT": { name: "VDE_UNDERFREQLIMIT", unit: "Hz" },
	"GRIDCONFIG.VDE_VOLTDROPPROT": { name: "VDE_VOLTDROPPROT", unit: "V" },
	"GRIDCONFIG.VDE_VOLTDROPPROTAVG": { name: "VDE_VOLTDROPPROTAVG", unit: "V" },
	"GRIDCONFIG.VDE_VOLTDROPPROTAVGDELAY": { name: "VDE_VOLTDROPPROTAVGDELAY", unit: "s" },
	"GRIDCONFIG.VDE_VOLTDROPPROTDELAY": { name: "VDE_VOLTDROPPROTDELAY", unit: "s" },
	"GRIDCONFIG.VDE_VOLTRISEPROT": { name: "VDE_VOLTRISEPROT", unit: "V" },
	"GRIDCONFIG.VDE_VOLTRISEPROTAVG": { name: "VDE_VOLTRISEPROTAVG", unit: "V" },
	"GRIDCONFIG.VDE_VOLTRISEPROTAVGDELAY": { name: "VDE_VOLTRISEPROTAVGDELAY", unit: "s" },
	"GRIDCONFIG.VDE_VOLTRISEPROTDELAY": { name: "VDE_VOLTRISEPROTDELAY", unit: "s" },
	GRID_EXPORT: { name: "GRID_EXPORT", unit: "kWh" },
	GRID_IMPORT: { name: "GRID_IMPORT", unit: "kWh" },
	"IPU.VERSION": { name: "VERSION" },
	"ISKRA.OBJECT_NOT_FOUND": { name: "OBJECT_NOT_FOUND" },
	"LOG.LOG_IN_BUTT": { name: "Log In Button", booltype: true },
	"LOG.LOG_IN_NOK_COUNT": { name: "LOG_IN_NOK_COUNT" },
	"LOG.LOG_OUT_BUTT": { name: "Log Out Button", booltype: true },
	"LOG.PASSWORD": { name: "Password" },
	"LOG.USERNAME": { name: "User Name" },
	"LOG.USER_LEVEL": { name: "User Level" },
	"PM1.MB_SL2MA_CONN": { name: "MB_SL2MA_CONN" },
	"PM1.MB_SLAVES_COUNT": { name: "MB_SLAVES_COUNT" },
	"PM1.PWR_METERS_MISSING": { name: "PWR_METERS_MISSING" },
	"PM1.TYPE": { name: "TYPE" },
	"PM1OBJ1.ADR": { name: "ADR" },
	"PM1OBJ1.ENABLED": { name: "EnFluRi-Netz.Aktiv", booltype: true },
	"PM1OBJ1.FREQ": { name: "EnFluRi-Netz.FREQ", unit: "Hz" },
	"PM1OBJ1.I_AC": { name: "EnFluRi-Netz.I_AC", unit: "A" },
	"PM1OBJ1.P_AC": { name: "EnFluRi-Netz.P_AC", unit: "W" },
	"PM1OBJ1.P_TOTAL": { name: "EnFluRi-Netz.P_TOTAL", unit: "W" },
	"PM1OBJ1.U_AC": { name: "EnFluRi-Netz.U_AC", unit: "V" },
	"PM1OBJ2.ADR": { name: "PM1OBJ2.ADR" },
	"PM1OBJ2.ENABLED": { name: "EnFluRi-Verbrauch.Aktiv", booltype: true },
	"PM1OBJ2.FREQ": { name: "EnFluRi-Verbrauch.FREQ", unit: "Hz" },
	"PM1OBJ2.I_AC": { name: "EnFluRi-Verbrauch.I_AC", unit: "A" },
	"PM1OBJ2.P_AC": { name: "EnFluRi-Verbrauch.P_AC", unit: "W" },
	"PM1OBJ2.P_TOTAL": { name: "EnFluRi-Verbrauch.P_TOTAL", unit: "W" },
	"PM1OBJ2.U_AC": { name: "EnFluRi-Verbrauch.U_AC", unit: "V" },
	POWER_CONSUMPTION: { name: "POWER_CONSUMPTION", unit: "kWh" },
	POWER_GENERATION: { name: "POWER_GENERATION", unit: "kWh" },
	"PV1.ERROR_STATE_INT": { name: "ERROR_STATE_INT" },
	"PV1.INTERNAL_INV_ERROR_TEXT": { name: "Internal inverter error text" },
	"PV1.INTERNAL_INV_ERR_STATE_VALID": { name: "Internal inverter error state valid", booltype: true },
	"PV1.INTERNAL_INV_STATE": { name: "Internal inverter state" },
	"PV1.INTERNAL_MD_AVAIL": { name: "Internal MD available", booltype: true },
	"PV1.INTERNAL_MD_MANUFACTURER": { name: "Internal MD manufacturer" },
	"PV1.INTERNAL_MD_MODEL": { name: "Internal MD model" },
	"PV1.INTERNAL_MD_SERIAL": { name: "Internal MD serial" },
	"PV1.INTERNAL_MD_VERSION": { name: "Internal MD version" },
	"PV1.INTERNAL_PV_AVAIL": { name: "Internal PV available", booltype: true },
	"PV1.INV_MODEL": { name: "Inverter model" },
	"PV1.INV_SERIAL": { name: "Inverter serial" },
	"PV1.INV_VERSIONS": { name: "Inverter versions" },
	"PV1.MPP_AVAIL": { name: "MPP available", booltype: true },
	"PV1.MPP_CUR": { name: "Energy DC", unit: "A" },
	"PV1.MPP_INT": { name: "Replaced by MPP_POWER", unit: "W" },
	"PV1.MPP_POWER": { name: "Power DC", unit: "W" },
	"PV1.MPP_VOL": { name: "Voltage DC", unit: "V" },
	"PV1.POWER_RATIO": { name: "PV1 Power Ratio", unit: "%" },
	"PV1.POWER_RATIO_L1": { name: "PV1 Power Ratio L1", unit: "%" },
	"PV1.POWER_RATIO_L2": { name: "PV1 Power Ratio L2", unit: "%" },
	"PV1.POWER_RATIO_L3": { name: "PV1 Power Ratio L3", unit: "%" },
	"PV1.PV_MISSING": { name: "PV_MISSING", booltype: true },
	"PV1.P_TOTAL": { name: "Power Total", unit: "W" },
	"PV1.STATE_INT": { name: "STATE_INT" },
	"PV1.TYPE": { name: "TYPE" },
	"PV1.VERSION1_INT": { name: "VERSION1_INT" },
	"PV1.VERSION2_INT": { name: "VERSION2_INT" },
	"PWR_UNIT.ADRESS": { name: "ADRESS" },
	"PWR_UNIT.CONNPWR": { name: "CONNPWR", unit: "W" },
	"PWR_UNIT.CONNPWR_1": { name: "CONNPWR_1", unit: "W" },
	"PWR_UNIT.CONNPWR_2": { name: "CONNPWR_2", unit: "W" },
	"PWR_UNIT.CONNPWR_3": { name: "CONNPWR_3", unit: "W" },
	"PWR_UNIT.CURRENTTEMP_MAX": { name: "CURRENTTEMP_MAX", unit: "°C" },
	"PWR_UNIT.CURRENTTEMP_MAX_HW": { name: "CURRENTTEMP_MAX_HW", unit: "°C" },
	"PWR_UNIT.CURRENTTEMP_MIN": { name: "CURRENTTEMP_MIN", unit: "°C" },
	"PWR_UNIT.CURRENTTEMP_MIN_HW": { name: "CURRENTTEMP_MIN_HW", unit: "°C" },
	"PWR_UNIT.ENFLURI": { name: "ENFLURI" },
	"PWR_UNIT.FW_VER": { name: "FW_VER" },
	"PWR_UNIT.HW_REV": { name: "HW_REV" },
	"PWR_UNIT.POWER": { name: "POWER", unit: "W" },
	"PWR_UNIT.POWER_L1": { name: "PWR_UNIT.POWER_L1", unit: "W" },
	"PWR_UNIT.POWER_L2": { name: "PWR_UNIT.POWER_L2", unit: "W" },
	"PWR_UNIT.POWER_L3": { name: "PWR_UNIT.POWER_L3", unit: "W" },
	"PWR_UNIT.PU_MISSING": { name: "PU_MISSING", booltype: true },
	"PWR_UNIT.REQ_POWER": { name: "REQ_POWER", unit: "W" },
	"PWR_UNIT.SERIAL": { name: "SERIAL" },
	"PWR_UNIT.STATUS": { name: "STATUS" },
	"PWR_UNIT.TEMPMAX": { name: "TEMPMAX", unit: "°C" },
	"PWR_UNIT.TEMPMIN": { name: "TEMPMIN", unit: "°C" },
	"PWR_UNIT.TEMPTARGET": { name: "TEMPTARGET", unit: "°C" },
	"PWR_UNIT.TEMP_COUNT": { name: "TEMP_COUNT" },
	"PWR_UNIT.TEMP_LIMIT_LOWER": { name: "TEMP_LIMIT_LOWER", unit: "°C" },
	"PWR_UNIT.TEMP_LIMIT_UPPER": { name: "TEMP_LIMIT_UPPER", unit: "°C" },
	"PWR_UNIT.TYPE": { name: "TYPE" },
	"PWR_UNIT.WATERVOL": { name: "WATERVOL", unit: "l" },
	"RTC.TIMESTAMP_MS": { name: "TIMESTAMP_MS" },
	"RTC.UTC_OFFSET": { name: "UTC_OFFSET" },
	"RTC.WEB_TIME": { name: "WEB_TIME", datetype: true },
	"SELFTEST_RESULTS.DC_COIL": { name: "DC_COIL" },
	"SELFTEST_RESULTS.INIT_BATTERY_MODULES": { name: "INIT_BATTERY_MODULES" },
	"SELFTEST_RESULTS.INSULATION": { name: "INSULATION" },
	"SELFTEST_RESULTS.INTERRUPT": { name: "INTERRUPT" },
	"SELFTEST_RESULTS.IPU": { name: "IPU" },
	"SENEC_IO_INPUT.AC_ERROR_IPU_V3": { name: "AC_ERROR_IPU_V3" },
	"SENEC_IO_INPUT.DC_HK_STATUS_IPU_V5": { name: "DC_HK_STATUS_IPU_V5" },
	"SENEC_IO_INPUT.DRY_CONTACT_IN_IPU_V5": { name: "DRY_CONTACT_IN_IPU_V5" },
	"SENEC_IO_INPUT.FAULTLINE": { name: "FAULTLINE" },
	"SENEC_IO_INPUT.FAULTLINE_DELAYED": { name: "FAULTLINE_DELAYED" },
	"SENEC_IO_INPUT.HID0": { name: "HID0" },
	"SENEC_IO_INPUT.HID1": { name: "HID1" },
	"SENEC_IO_INPUT.HID2_IPU_V5": { name: "HID2_IPU_V5" },
	"SENEC_IO_INPUT.HID3_IPU_V5": { name: "HID3_IPU_V5" },
	"SENEC_IO_INPUT.ISOGUARD_STATUS": { name: "ISOGUARD_STATUS" },
	"SENEC_IO_INPUT.POWER_STATUS": { name: "POWER_STATUS" },
	"SENEC_IO_INPUT.RCD_DC_IPU_V3": { name: "RCD_DC_IPU_V3" },
	"SENEC_IO_INPUT.RCD_ERROR_IPU_V3": { name: "RCD_ERROR_IPU_V3" },
	"SENEC_IO_INPUT.RCD_RMS_IPU_V3": { name: "RCD_RMS_IPU_V3" },
	"SENEC_IO_INPUT.STATUS_AC_SWITCH_IPU_V3": { name: "STATUS_AC_SWITCH_IPU_V3" },
	"SENEC_IO_INPUT.STATUS_DC_SWITCH_IPU_V5": { name: "STATUS_DC_SWITCH_IPU_V5" },
	"SENEC_IO_OUTPUT.AC_SWITCH_IPU_V3": { name: "AC_SWITCH_IPU_V3", booltype: true },
	"SENEC_IO_OUTPUT.BAT_MODULE_ENABLE_AMPACE": { name: "SENEC_IO_OUTPUT.BAT_MODULE_ENABLE_AMPACE", booltype: true },
	"SENEC_IO_OUTPUT.BAT_MODULE_ENABLE_BMZ": { name: "BAT_MODULE_ENABLE_BMZ", booltype: true },
	"SENEC_IO_OUTPUT.BAT_MODULE_ENABLE_DETECTION": {
		name: "SENEC_IO_OUTPUT.BAT_MODULE_ENABLE_DETECTION",
		booltype: true,
	},
	"SENEC_IO_OUTPUT.BAT_MODULE_ENABLE_SAMSUNG_IPU_V5": { name: "BAT_MODULE_ENABLE_SAMSUNG_IPU_V5", booltype: true },
	"SENEC_IO_OUTPUT.BMS_enable": { name: "BMS_enable", booltype: true },
	"SENEC_IO_OUTPUT.DC_SWITCH": { name: "DC_SWITCH", booltype: true },
	"SENEC_IO_OUTPUT.DC_coil": { name: "DC_coil" },
	"SENEC_IO_OUTPUT.DRY_CONTACT_OUT_IPU_V5": { name: "DRY_CONTACT_OUT_IPU_V5", booltype: true },
	"SENEC_IO_OUTPUT.FAULTLINE_DELAYED_DUALUSE": { name: "FAULTLINE_DELAYED_DUALUSE", booltype: true },
	"SENEC_IO_OUTPUT.ISOGUARD_ENABLE": { name: "ISOGUARD_ENABLE", booltype: true },
	"SENEC_IO_OUTPUT.KILLSWITCH": { name: "KILLSWITCH", booltype: true },
	"SENEC_IO_OUTPUT.Killswitch": { name: "Killswitch", booltype: true },
	"SENEC_IO_OUTPUT.RCD_RESET_IPU_V3": { name: "RCD_RESET_IPU_V3", booltype: true },
	"SENEC_IO_OUTPUT.RCD_TEST_IPU_V3": { name: "RCD_TEST_IPU_V3", booltype: true },
	"SENEC_IO_OUTPUT.Relay_1": { name: "Relay_1" },
	"SENEC_IO_OUTPUT.Relay_2": { name: "Relay_2" },
	"SENEC_IO_OUTPUT.Relay_3": { name: "Relay_3" },
	"SENEC_IO_OUTPUT.Relay_4": { name: "Relay_4" },
	"SENEC_IO_OUTPUT.STECA_BUS_ENABLE": { name: "SENEC_IO_OUTPUT.STECA_BUS_ENABLE", booltype: true },
	"SOCKETS.ALREADY_SWITCHED": { name: "ALREADY_SWITCHED", booltype: true },
	"SOCKETS.ENABLE": { name: "ENABLE", booltype: true },
	"SOCKETS.FORCE_ON": { name: "FORCE_ON", booltype: true },
	"SOCKETS.LOWER_LIMIT": { name: "LOWER_LIMIT" },
	"SOCKETS.NUMBER_OF_SOCKETS": { name: "NUMBER_OF_SOCKETS" },
	"SOCKETS.POWER_ON": { name: "POWER_ON", booltype: true },
	"SOCKETS.POWER_ON_TIME": { name: "POWER_ON_TIME", booltype: true },
	"SOCKETS.PRIORITY": { name: "PRIORITY" },
	"SOCKETS.RESET_SWITCHED": { name: "RESET_SWITCHED", booltype: true },
	"SOCKETS.SWITCH_ON_HOUR": { name: "SWITCH_ON_HOUR" },
	"SOCKETS.SWITCH_ON_MINUTE": { name: "SWITCH_ON_MINUTE" },
	"SOCKETS.TIME_LIMIT": { name: "TIME_LIMIT" },
	"SOCKETS.TIME_REM": { name: "TIME_REM" },
	"SOCKETS.UPPER_LIMIT": { name: "UPPER_LIMIT" },
	"SOCKETS.USE_TIME": { name: "USE_TIME" },
	"STECA.BAT": { name: "Bat" },
	"STECA.BDC_STATE": { name: "BDC State" },
	"STECA.ERROR": { name: "Error" },
	"STECA.ERRORTEXT": { name: "Error text" },
	"STECA.ISLAND": { name: "Island" },
	"STECA.NUM_PV_CONFIG_POSSIBLE": { name: "# PV config possible" },
	"STECA.PV": { name: "PV" },
	"STECA.PVSS": { name: "PVSS" },
	"STECA.PV_CONFIG_POSSIBLE": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.0": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.1": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.2": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.3": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.4": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.5": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.6": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.7": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.8": { name: "PV config possible", booltype: true },
	"STECA.PV_CONFIG_POSSIBLE.9": { name: "PV config possible", booltype: true },
	"STECA.PV_INPUTS": { name: "PV Inputs" },
	"STECA.RELAYS": { name: "RELAYS" },
	"STECA.STARTUP": { name: "STARTUP" },
	"STECA.STARTUP_ADD": { name: "Startup add" },
	"SYS_UPDATE.BOOTLOADER_VERSION": { name: "Bootloader Version" },
	"SYS_UPDATE.BOOT_REPORT_SUCCESS": { name: "Boot Report Success", booltype: true },
	"SYS_UPDATE.FEATURE_OVERWRITE": { name: "Feature Overwrite", booltype: true },
	"SYS_UPDATE.FSM_STATE": { name: "FSM State" },
	"SYS_UPDATE.MISC": { name: "MISC" },
	"SYS_UPDATE.NO_SERVER_CONN_TIME": { name: "No Server Connection Time", datetype: true },
	"SYS_UPDATE.NPU_IMAGE_VERSION": { name: "Revision NPU - Image" },
	"SYS_UPDATE.NPU_VER": { name: "Revision NPU - REGS" },
	"SYS_UPDATE.TRIGGER_BL_UPDATE": { name: "Triggered BL update", booltype: true },
	"SYS_UPDATE.UPDATE_AVAILABLE": { name: "Update available", booltype: true },
	"SYS_UPDATE.USER_REBOOT_DEVICE": { name: "User Reboot Device", booltype: true },
	"SYS_UPDATE.USER_REQ_INV_UPDATE": { name: "User Requested INV Update", booltype: true },
	"SYS_UPDATE.USER_REQ_NA_UPDATE": { name: "User Requested NA Update", booltype: true },
	"SYS_UPDATE.USER_REQ_UPDATE": { name: "User Requested Update", booltype: true },
	"TEMPMEASURE.BATTERY_TEMP": { name: "TEMPMEASURE.BATTERY_TEMP", unit: "°C" },
	"TEMPMEASURE.CASE_TEMP": { name: "TEMPMEASURE.CASE_TEMP", unit: "°C" },
	"TEMPMEASURE.MCU_TEMP": { name: "TEMPMEASURE.MCU_TEMP", unit: "°C" },
	"TEMPMEASURE.TEMP_DATA_COLLECTED": { name: "TEMPMEASURE.MCU_TEMP", booltype: true },
	"TEST.ENABLE": { name: "ENABLE", booltype: true },
	"TEST.INPUT": { name: "INPUT" },
	"TEST.OUTPUT": { name: "OUTPUT" },
	"TEST.RESULT": { name: "RESULT" },
	"TEST.START": { name: "START" },
	"TEST.TYPE": { name: "TYPE" },
	"WALLBOX.ADDITIONAL_ERROR": { name: "WALLBOX.ADDITIONAL_ERROR" },
	"WALLBOX.ALLOW_INTERCHARGE": { name: "ALLOW_INTERCHARGE" },
	"WALLBOX.APPARENT_CHARGING_POWER": { name: "WALLBOX.APPARENT_CHARGING_POWER", unit: "W" },
	"WALLBOX.BUS_ADR": { name: "Bus ADR" },
	"WALLBOX.CS_ENABLED": { name: "WALLBOX.CS_ENABLED", booltype: true },
	"WALLBOX.CS_ENABLED.0": { name: "WALLBOX.CS_ENABLED", booltype: true },
	"WALLBOX.CS_ENABLED.1": { name: "WALLBOX.CS_ENABLED", booltype: true },
	"WALLBOX.CS_ENABLED.2": { name: "WALLBOX.CS_ENABLED", booltype: true },
	"WALLBOX.CS_ENABLED.3": { name: "WALLBOX.CS_ENABLED", booltype: true },
	"WALLBOX.DETECTION_MODE": { name: "Detection Mode" },
	"WALLBOX.ERROR_DETAILS": { name: "ERROR_DETAILS" },
	"WALLBOX.EV_CONNECTED": { name: "WALLBOX.EV_CONNECTED", booltype: true },
	"WALLBOX.EV_CONNECTED.0": { name: "WALLBOX.EV_CONNECTED", booltype: true },
	"WALLBOX.EV_CONNECTED.1": { name: "WALLBOX.EV_CONNECTED", booltype: true },
	"WALLBOX.EV_CONNECTED.2": { name: "WALLBOX.EV_CONNECTED", booltype: true },
	"WALLBOX.EV_CONNECTED.3": { name: "WALLBOX.EV_CONNECTED", booltype: true },
	"WALLBOX.HW_TYPE": { name: "WALLBOX.HW_TYPE" },
	"WALLBOX.ID": { name: "WALLBOX.ID" },
	"WALLBOX.L1_CHARGING_CURRENT": { name: "WALLBOX.L1_CHARGING_CURRENT", unit: "A" },
	"WALLBOX.L1_USED": { name: "WALLBOX.L1_USED", booltype: true },
	"WALLBOX.L1_USED.0": { name: "WALLBOX.L1_USED", booltype: true },
	"WALLBOX.L1_USED.1": { name: "WALLBOX.L1_USED", booltype: true },
	"WALLBOX.L1_USED.2": { name: "WALLBOX.L1_USED", booltype: true },
	"WALLBOX.L1_USED.3": { name: "WALLBOX.L1_USED", booltype: true },
	"WALLBOX.L2_CHARGING_CURRENT": { name: "WALLBOX.L2_CHARGING_CURRENT", unit: "A" },
	"WALLBOX.L2_USED": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L2_USED.0": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L2_USED.1": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L2_USED.2": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L2_USED.3": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L3_CHARGING_CURRENT": { name: "WALLBOX.L3_CHARGING_CURRENT", unit: "A" },
	"WALLBOX.L3_USED": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L3_USED.0": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L3_USED.1": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L3_USED.2": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.L3_USED.3": { name: "WALLBOX.L3_USED", booltype: true },
	"WALLBOX.LOAD_IMBALANCE_DETECTED": { name: "Load imbalance detected", booltype: true },
	"WALLBOX.LOAD_IMBALANCE_ENABLED": { name: "Load imbalance enabled", booltype: true },
	"WALLBOX.LOAD_IMBALANCE_ENABLED.0": { name: "Load imbalance enabled", booltype: true },
	"WALLBOX.LOAD_IMBALANCE_ENABLED.1": { name: "Load imbalance enabled", booltype: true },
	"WALLBOX.LOAD_IMBALANCE_ENABLED.2": { name: "Load imbalance enabled", booltype: true },
	"WALLBOX.LOAD_IMBALANCE_ENABLED.3": { name: "Load imbalance enabled", booltype: true },
	"WALLBOX.MAJOR_REV": { name: "WALLBOX.MAJOR_REV" },
	"WALLBOX.MAX_CHARGING_CURRENT_DEFAULT": { name: "WALLBOX.MAX_CHARGING_CURRENT_DEFAULT", unit: "A" },
	"WALLBOX.MAX_CHARGING_CURRENT_IC": { name: "WALLBOX.MAX_CHARGING_CURRENT_IC", unit: "A" },
	"WALLBOX.MAX_CHARGING_CURRENT_ICMAX": { name: "WALLBOX.MAX_CHARGING_CURRENT_ICMAX", unit: "A" },
	"WALLBOX.MAX_CHARGING_CURRENT_RATED": { name: "WALLBOX.MAX_CHARGING_CURRENT_RATED", unit: "A" },
	"WALLBOX.MAX_PHASE_CURRENT_BY_GRID": { name: "MAX_PHASE_CURRENT_BY_GRID", unit: "A" },
	"WALLBOX.MAX_TOTAL_CURRENT_BY_GRID": { name: "MAX_TOTAL_CURRENT_BY_GRID", unit: "A" },
	"WALLBOX.METER_ENABLED": { name: "WALLBOX.METER_ENABLED", booltype: true },
	"WALLBOX.METER_ENABLED.0": { name: "WALLBOX.METER_ENABLED", booltype: true },
	"WALLBOX.METER_ENABLED.1": { name: "WALLBOX.METER_ENABLED", booltype: true },
	"WALLBOX.METER_ENABLED.2": { name: "WALLBOX.METER_ENABLED", booltype: true },
	"WALLBOX.METER_ENABLED.3": { name: "WALLBOX.METER_ENABLED", booltype: true },
	"WALLBOX.METHOD_EN1": { name: "WALLBOX.METHOD_EN1" },
	"WALLBOX.MINOR_REV": { name: "WALLBOX.MINOR_REV" },
	"WALLBOX.MIN_CHARGING_CURRENT": { name: "MIN_CHARGING_CURRENT", unit: "A" },
	"WALLBOX.NUMBER_OF_PHASE": { name: "NUMBER_OF_PHASE" },
	"WALLBOX.PHASES_USED": { name: "WALLBOX.PHASES_USED" },
	"WALLBOX.PHASES_USED.0": { name: "WALLBOX.PHASES_USED", booltype: true },
	"WALLBOX.PHASES_USED.1": { name: "WALLBOX.PHASES_USED", booltype: true },
	"WALLBOX.PHASES_USED.2": { name: "WALLBOX.PHASES_USED", booltype: true },
	"WALLBOX.PHASES_USED.3": { name: "WALLBOX.PHASES_USED", booltype: true },
	"WALLBOX.PROHIBIT_USAGE": { name: "Prohibit usage", booltype: true },
	"WALLBOX.PROHIBIT_USAGE.0": { name: "Prohibit usage", booltype: true },
	"WALLBOX.PROHIBIT_USAGE.1": { name: "Prohibit usage", booltype: true },
	"WALLBOX.PROHIBIT_USAGE.2": { name: "Prohibit usage", booltype: true },
	"WALLBOX.PROHIBIT_USAGE.3": { name: "Prohibit usage", booltype: true },
	"WALLBOX.SAP_NUMBER": { name: "SAP number" },
	"WALLBOX.SERIAL_NUMBER": { name: "Serial number" },
	"WALLBOX.SERIAL_NUMBER_INTERNAL": { name: "Serial number internal" },
	"WALLBOX.SET_ICMAX": { name: "SET_ICMAX", unit: "A" },
	"WALLBOX.SET_IDEFAULT": { name: "SET_IDEFAULT", unit: "A" },
	"WALLBOX.SET_IDEFAULT.1 ": { name: "SET_IDEFAULT 1", unit: "A" },
	"WALLBOX.SET_IDEFAULT.2": { name: "SET_IDEFAULT 2", unit: "A" },
	"WALLBOX.SET_IDEFAULT.3": { name: "SET_IDEFAULT 3", unit: "A" },
	"WALLBOX.SMART_CHARGE_ACTIVE": { name: "Smart charge active", booltype: true },
	"WALLBOX.SMART_CHARGE_ACTIVE.0": { name: "Smart charge active 0", booltype: true },
	"WALLBOX.SMART_CHARGE_ACTIVE.1": { name: "Smart charge active 1", booltype: true },
	"WALLBOX.SMART_CHARGE_ACTIVE.2": { name: "Smart charge active 2", booltype: true },
	"WALLBOX.SMART_CHARGE_ACTIVE.3": { name: "Smart charge active 3", booltype: true },
	"WALLBOX.SOCKET_ENABLED": { name: "WALLBOX.SOCKET_ENABLED", booltype: true },
	"WALLBOX.SOCKET_ENABLED.0": { name: "WALLBOX.SOCKET_ENABLED 0", booltype: true },
	"WALLBOX.SOCKET_ENABLED.1": { name: "WALLBOX.SOCKET_ENABLED 1", booltype: true },
	"WALLBOX.SOCKET_ENABLED.2": { name: "WALLBOX.SOCKET_ENABLED 2", booltype: true },
	"WALLBOX.SOCKET_ENABLED.3": { name: "SOCKET_ENABLED 3", booltype: true },
	"WALLBOX.STATE": { name: "Wallbox Status" },
	"WALLBOX.STATE_Text": { name: "Wallbox Status" },
	"WALLBOX.UID": { name: "UID" },
	"WALLBOX.UTMP": { name: "WALLBOX.UTMP", unit: "°C" },
	WALLBOX_CONSUMPTION: { name: "WALLBOX_CONSUMPTION", unit: "kWh" },
	"WIZARD.APPLICATION_HASH": { name: "Application Hash" },
	"WIZARD.APPLICATION_VERSION": { name: "Revision MCU" },
	"WIZARD.BATT_IPU_MISMATCH": { name: "BATT_IPU_MISMATCH", booltype: true },
	"WIZARD.BOOT": { name: "BOOT" },
	"WIZARD.CHARGE_PRIO": { name: "Charge Priority" },
	"WIZARD.CONFIG_CHECKSUM": { name: "Configuration Checksum" },
	"WIZARD.CONFIG_LOADED": { name: "Configuration loaded", booltype: true },
	"WIZARD.CONFIG_MODIFIED_BY_USER": { name: "Configuration modified by user", booltype: true },
	"WIZARD.CONFIG_WRITE": { name: "Config write", booltype: true },
	"WIZARD.DEVICE_BATTERY_ENABLED": { name: "Device Battery enabled", booltype: true },
	"WIZARD.DEVICE_BATTERY_TYPE": { name: "Device Battery Type" },
	"WIZARD.DEVICE_INVERTER_TYPE": { name: "Device Inverter Type" },
	"WIZARD.DEVICE_INV_ENABLED": { name: "Device Inverter Enabled", booltype: true },
	"WIZARD.DEVICE_INV_ENABLED.0": { name: "Device Inverter Enabled 0", booltype: true },
	"WIZARD.DEVICE_INV_ENABLED.1": { name: "Device Inverter Enabled 1", booltype: true },
	"WIZARD.DEVICE_INV_ENABLED.2": { name: "Device Inverter Enabled 2", booltype: true },
	"WIZARD.DEVICE_INV_ENABLED.3": { name: "Device Inverter Enabled 3", booltype: true },
	"WIZARD.DEVICE_INV_ENABLED.4": { name: "Device Inverter Enabled 4", booltype: true },
	"WIZARD.DEVICE_INV_ENABLED.5": { name: "Device Inverter Enabled 5", booltype: true },
	"WIZARD.DEVICE_INV_PHASES_ARR": { name: "Device Inverter Phases" },
	"WIZARD.DEVICE_INV_SLAVE_ADRESS": { name: "Device Inverter Slave Adress" },
	"WIZARD.DEVICE_PM_GRID_ENABLED": { name: "Device PM Grid Enabled", booltype: true },
	"WIZARD.DEVICE_PM_HOUSE_ENABLED": { name: "Device PM House enabled", booltype: true },
	"WIZARD.DEVICE_PM_TYPE": { name: "Device PM Type" },
	"WIZARD.DEVICE_WB_TYPE": { name: "Device WB Type" },
	"WIZARD.FEATURECODE_ENTERED": { name: "Featurecode entered", booltype: true },
	"WIZARD.FIRMWARE_VERSION": { name: "Firmware Version" },
	"WIZARD.GENERATION_METER_SN": { name: "Generation Meter Serialnumber" },
	"WIZARD.GRID_CONNECTION_TYPE": { name: "Grid Connection Type" },
	"WIZARD.GUI_LANG": { name: "GUI Language" },
	"WIZARD.HEATPUMP_METER_SN": { name: "HEATPUMP_METER_SN" },
	"WIZARD.HEAT_CONN_TYPE": { name: "HEAT_CONN_TYPE" },
	"WIZARD.INSULATION_RESISTANCE": { name: "INSULATION_RESISTANCE" },
	"WIZARD.INTERFACE_VERSION": { name: "Revision GUI" },
	"WIZARD.LOGGER_SEVERITY": { name: "LOGGER_SEVERITY" },
	"WIZARD.MAC_ADDRESS_BYTES": { name: "MAC Address Bytes" },
	"WIZARD.MASTER_SLAVE_ADDRESSES": { name: "Master Slave Addresses" },
	"WIZARD.MASTER_SLAVE_MODE": { name: "Master Slave Mode", booltype: true },
	"WIZARD.NET_DNS_SERVER_IP": { name: "NET_DNS_SERVER_IP", iptype: true },
	"WIZARD.NET_GATEWAY_IP": { name: "NET_GATEWAY_IP", iptype: true },
	"WIZARD.NET_NETWORK_MASK": { name: "NET_NETWORK_MASK", iptype: true },
	"WIZARD.NET_SENEC_NO_NETWORK": { name: "NET_SENEC_NO_NETWORK", booltype: true },
	"WIZARD.NET_SENEC_SERVER_IP": { name: "NET_SENEC_SERVER_IP", iptype: true },
	"WIZARD.NET_SENEC_STATIC_IP": { name: "NET_SENEC_STATIC_IP", iptype: true },
	"WIZARD.NET_SENEC_USE_DHCP": { name: "NET_SENEC_USE_DHCP", booltype: true },
	"WIZARD.POWER_METER_SERIAL": { name: "Power Meter Serial" },
	"WIZARD.PS_ENABLE": { name: "PeakShaving ENABLE", booltype: true },
	"WIZARD.PS_HOUR": { name: "PeakShaving hour" },
	"WIZARD.PS_MINUTE": { name: "PeakShaving Minute" },
	"WIZARD.PS_RESERVOIR": { name: "PeakShaving Reservoir", unit: "%" },
	"WIZARD.PV_CONFIG": { name: "PV_CONFIG" },
	"WIZARD.PV_CONFIG.0": { name: "PV_CONFIG 0", booltype: true },
	"WIZARD.PV_CONFIG.1": { name: "PV_CONFIG 1", booltype: true },
	"WIZARD.PWRCFG_PEAK_PV_POWER": { name: "Configured Peak PV Power", unit: "W" },
	"WIZARD.SENEC_METER_SN": { name: "SENEC_METER_SN" },
	"WIZARD.SETUP_ABS_POWER": { name: "SETUP_ABS_POWER" },
	"WIZARD.SETUP_AGBS_ACCEPTED": { name: "SETUP_AGBS_ACCEPTED", booltype: true },
	"WIZARD.SETUP_HV_PHASE": { name: "SETUP_HV_PHASE", booltype: true },
	"WIZARD.SETUP_NUMBER_WALLBOXES": { name: "# Wallboxes" },
	"WIZARD.SETUP_PM_GRID_ADR": { name: "SETUP_PM_GRID_ADR" },
	"WIZARD.SETUP_PM_HOUSE_ADR": { name: "SETUP_PM_HOUSE_ADR" },
	"WIZARD.SETUP_POWER_RULE": { name: "SETUP_POWER_RULE", unit: "%" },
	"WIZARD.SETUP_PV_INV_IP0": { name: "SETUP_PV_INV_IP0", iptype: true },
	"WIZARD.SETUP_PV_INV_IP1": { name: "SETUP_PV_INV_IP1", iptype: true },
	"WIZARD.SETUP_PV_INV_IP2": { name: "SETUP_PV_INV_IP2", iptype: true },
	"WIZARD.SETUP_PV_INV_IP3": { name: "SETUP_PV_INV_IP3", iptype: true },
	"WIZARD.SETUP_PV_INV_IP4": { name: "SETUP_PV_INV_IP4", iptype: true },
	"WIZARD.SETUP_PV_INV_IP5": { name: "SETUP_PV_INV_IP5", iptype: true },
	"WIZARD.SETUP_RCR_STEPS": { name: "Setup RCR Steps" },
	"WIZARD.SETUP_USED_PHASE": { name: "SETUP_USED_PHASE" },
	"WIZARD.SETUP_USE_ABS_POWER": { name: "SETUP_USE_ABS_POWER", booltype: true },
	"WIZARD.SETUP_USE_DRM0": { name: "SETUP_USE_DRM0", booltype: true },
	"WIZARD.SETUP_USE_RCR": { name: "SETUP_USE_RCR", booltype: true },
	"WIZARD.SETUP_WALLBOX_IDS": { name: "Setup Wallbox IDs" },
	"WIZARD.SETUP_WALLBOX_MAX_TOTAL_CURRENT_BY_GRID": { name: "SETUP_WALLBOX_MAX_TOTAL_CURRENT_BY_GRID", unit: "A" },
	"WIZARD.SETUP_WALLBOX_SERIAL0": { name: "Wallbox 0 Serial" },
	"WIZARD.SETUP_WALLBOX_SERIAL1": { name: "Wallbox 1 Serial" },
	"WIZARD.SETUP_WALLBOX_SERIAL2": { name: "Wallbox 2 Serial" },
	"WIZARD.SETUP_WALLBOX_SERIAL3": { name: "Wallbox 3 Serial" },
	"WIZARD.SG_READY_CURR_MODE": { name: "SG_READY_CURR_MODE" },
	"WIZARD.SG_READY_ENABLED": { name: "SG_READY_ENABLED", booltype: true },
	"WIZARD.SG_READY_ENABLE_OVERWRITE": { name: "SG_READY_ENABLE_OVERWRITE", booltype: true },
	"WIZARD.SG_READY_EN_MODE1": { name: "SG_READY_EN_MODE1" },
	"WIZARD.SG_READY_OVERWRITE_RELAY": { name: "SG_READY_OVERWRITE_RELAY", booltype: true },
	"WIZARD.SG_READY_OVERWRITE_RELAY.0": { name: "SG_READY_OVERWRITE_RELAY 0", booltype: true },
	"WIZARD.SG_READY_OVERWRITE_RELAY.1": { name: "SG_READY_OVERWRITE_RELAY 1", booltype: true },
	"WIZARD.SG_READY_POWER_COMM": { name: "SG_READY_POWER_COMM" },
	"WIZARD.SG_READY_POWER_NORMAL": { name: "SG_READY_POWER_NORMAL", booltype: true },
	"WIZARD.SG_READY_POWER_PROP": { name: "SG_READY_POWER_PROP" },
	"WIZARD.SG_READY_TIME": { name: "SG_READY_TIME" },
	"WIZARD.TECH_BUNDLE_CODE_SGREADY": { name: "TECH_BUNDLE_CODE_SGREADY" },
	"WIZARD.TECH_BUNDLE_CODE_SOCKETS": { name: "TECH_BUNDLE_CODE_SOCKETS" },
	"WIZARD.TECH_BUNDLE_INSTALLED": { name: "TECH_BUNDLE_INSTALLED", booltype: true },
	"WIZARD.TEST_EG_METER": { name: "TEST_EG_METER", booltype: true },
	"WIZARD.TEST_GENERATION_METER": { name: "TEST_GENERATION_METER", booltype: true },
	"WIZARD.TEST_HEATPUMP_METER": { name: "TEST_HEATPUMP_METER", booltype: true },
	"WIZARD.TEST_SENEC_METER": { name: "TEST_SENEC_METER", booltype: true },
	"WIZARD.USE_TESTSERVER": { name: "USE_TESTSERVER", booltype: true },
	"WIZARD.ZEROMODULE": { name: "ZEROMODULE" },
	abschaltschwelleInWatt: { name: "Switch-off Threshold", unit: "W" },
	"accuexport.now": { name: "Battery Charge (current)", unit: "W" },
	"accuexport.today": { name: "Battery Charge (today)", unit: "kWh" },
	"accuimport.now": { name: "Battery Discharge (current)", unit: "W" },
	"accuimport.today": { name: "Battery Discharge (today)", unit: "kWh" },
	"acculevel.now": { name: "Battery Level (current)", unit: "%" },
	"acculevel.today": { name: "Battery Level (today)", unit: "%" },
	akkuVisible: { name: "Battery Visible", booltype: true },
	anzahlAnlagen: { name: "Number of Systems" },
	autarkieVisible: { name: "Autarky Visible", booltype: true },
	"battery.current": { name: "Battery Current", unit: "A" },
	"battery.power": { name: "Battery Power", unit: "W" },
	"battery.state": { name: "Battery State" },
	"battery.state_of_charge": { name: "Battery SoC", unit: "%" },
	"battery.voltage": { name: "Battery Voltage", unit: "V" },
	"batteryInverter.state.name": { name: "Inverter State" },
	"batteryInverter.state.severity": { name: "Inverter State Severity" },
	"batteryInverter.temperatures.amb": { name: "Inverter Ambient Temperature", unit: "°C" },
	"batteryInverter.temperatures.halfBridge1": { name: "Half Bridge 1 Temperature", unit: "°C" },
	"batteryInverter.temperatures.halfBridge2": { name: "Half Bridge 2 Temperature", unit: "°C" },
	"batteryInverter.temperatures.max": { name: "Inverter Max Temperature", unit: "°C" },
	"batteryInverter.temperatures.throttle": { name: "Throttle Temperature", unit: "°C" },
	"batteryModules.firmwareVersion": { name: "Module Firmware Version" },
	"batteryModules.lastContact.severity": { name: "Module Last Contact Severity" },
	"batteryModules.lastContact.timestamp": { name: "Module Last Contact" },
	"batteryModules.maxTemperature": { name: "Module Max Temperature", unit: "°C" },
	"batteryModules.minTemperature": { name: "Module Min Temperature", unit: "°C" },
	"batteryModules.ordinal": { name: "Module Ordinal" },
	"batteryModules.serialNumber": { name: "Module Serial Number" },
	"batteryModules.state.severity": { name: "Module State Severity" },
	"batteryModules.state.state": { name: "Module State" },
	"batteryPack.bmsFirmwareVersion": { name: "BMS Firmware Version" },
	"batteryPack.currentChargingLevelInPercent": { name: "Charging Level", unit: "%" },
	"batteryPack.currentCurrentInA": { name: "Battery Current", unit: "A" },
	"batteryPack.currentVoltageInV": { name: "Battery Voltage", unit: "V" },
	"batteryPack.maxCapacityInKwh": { name: "Max Capacity", unit: "kWh" },
	"batteryPack.maxChargingPowerInKw": { name: "Max Charging Power", unit: "kW" },
	"batteryPack.maxDischargingPowerInKw": { name: "Max Discharging Power", unit: "kW" },
	"batteryPack.numberOfBatteryModules": { name: "Number of Battery Modules" },
	"batteryPack.remainingCapacityInPercent": { name: "Remaining Capacity (SOH)", unit: "%" },
	"batteryPack.technology": { name: "Battery Technology" },
	"bearbeiter.aktiv": { name: "Editor Active", booltype: true },
	"bearbeiter.geloescht": { name: "Editor Deleted", booltype: true },
	"bearbeiter.id": { name: "Editor ID" },
	"bearbeiter.userRole": { name: "Editor Role" },
	bearbeitungsdatum: { name: "Last Edit Date", datetype: true },
	"bessNameplate.active_charge_power": { name: "Max Charge Power", unit: "W" },
	"bessNameplate.active_discharge_power": { name: "Max Discharge Power", unit: "W" },
	"bessNameplate.design_capacity": { name: "Design Capacity", unit: "Wh" },
	"bessNameplate.manufacturer": { name: "Manufacturer" },
	"bessNameplate.model": { name: "Model" },
	"bessNameplate.serial_number": { name: "Serial Number" },
	"capabilities.hideForecastBasedCharging": { name: "hideForecastBasedCharging", booltype: true },
	"capabilities.hidePowerPilot": { name: "hidePowerPilot", booltype: true },
	"capabilities.hideWallboxComfortCharging": { name: "hideWallboxComfortCharging", booltype: true },
	"capabilities.hideWallboxExpertFastChargingSettings": {
		name: "hideWallboxExpertFastChargingSettings",
		booltype: true,
	},
	"capabilities.hideWallboxSolarExertSettings": { name: "hideWallboxSolarExertSettings", booltype: true },
	"capabilities.hideWallboxSolarExpertSettings": { name: "hideWallboxSolarExpertSettings", booltype: true },
	"capabilities.hideWallboxSolarOptimizedCharging": { name: "hideWallboxSolarOptimizedCharging", booltype: true },
	"capabilities.isSgReadySupported": { name: "isSgReadySupported", booltype: true },
	cascadeDevicesCount: { name: "Number of cascaded Devices" },
	caseNumber: { name: "caseNumber" },
	"casing.serial": { name: "Casing Serial" },
	"casing.temperatureInCelsius": { name: "Casing Temperature", unit: "°C" },
	chargingMode: { name: "Charging Mode" },
	city: { name: "city" },
	"consumption.now": { name: "Consumption (current)", unit: "W" },
	"consumption.today": { name: "Consumption (today)", unit: "kWh" },
	controlUnitNumber: { name: "controlUnitNumber" },
	countryCode: { name: "countryCode" },
	"currently.batteryChargeInW": { name: "batteryChargeInW", unit: "W" },
	"currently.batteryDischargeInW": { name: "batteryDischargeInW", unit: "W" },
	"currently.batteryLevelInPercent": { name: "batteryLevelInPercent", unit: "%" },
	"currently.gridDrawInW": { name: "gridDrawInW", unit: "W" },
	"currently.gridFeedInInW": { name: "gridFeedInInW", unit: "W" },
	"currently.powerConsumptionInW": { name: "powerConsumptionInW", unit: "W" },
	"currently.powerGenerationInW": { name: "powerGenerationInW", unit: "W" },
	"currently.selfSufficiencyInPercent": { name: "selfSufficiencyInPercent", unit: "%" },
	"currently.wallboxInW": { name: "wallboxInW", unit: "W" },
	dauerLeistungsueberschussInMin: { name: "Power Surplus Duration", unit: "min" },
	dauerSteckdoseAnInMin: { name: "Socket On Duration", unit: "min" },
	devNumber: { name: "Device Number" },
	digitalAssistantVisible: { name: "Digital Assistant Visible", booltype: true },
	disclaimerAccepted: { name: "Disclaimer Accepted", booltype: true },
	dokumenteVisible: { name: "Documents Visible", booltype: true },
	einschaltschwelleInWatt: { name: "Switch-on Threshold", unit: "W" },
	"einschaltzeit.0": { name: "Switch-on Hour" },
	"einschaltzeit.1": { name: "Switch-on Minute" },
	einspeisebegrenzungKwpInPercent: { name: "Feed-In Limit", unit: "%" },
	electricVehicleConnected: { name: "electricVehicleConnected", booltype: true },
	emailAdresse: { name: "Email Address" },
	emergencyPowerVisible: { name: "Emergency Power Visible", booltype: true },
	"evse.charging_power": { name: "Charging Power", unit: "VA" },
	"evse.ev_charging": { name: "EV Charging", booltype: true },
	"evse.ev_connected": { name: "EV Connected", booltype: true },
	"evse.id": { name: "Wallbox ID" },
	firmwareVersion: { name: "Firmware Version" },
	"gridexport.now": { name: "Grid Export (current)", unit: "W" },
	"gridexport.today": { name: "Grid Export (today)", unit: "kWh" },
	"gridimport.now": { name: "Grid Import (current)", unit: "W" },
	"gridimport.today": { name: "Grid Import (today)", unit: "kWh" },
	guiVersion: { name: "GUI Version" },
	heizstaebeVisible: { name: "Heating Rod Visible", booltype: true },
	houseNumber: { name: "houseNumber" },
	id: { name: "id" },
	"installer.address.city": { name: "Installer City" },
	"installer.address.countryCode": { name: "Installer Country" },
	"installer.address.houseNumber": { name: "Installer House Number" },
	"installer.address.postcode": { name: "Installer Postcode" },
	"installer.address.region": { name: "Installer Region" },
	"installer.address.street": { name: "Installer Street" },
	"installer.address.timezone": { name: "Installer Timezone" },
	"installer.companyName": { name: "Installer Company" },
	"installer.email": { name: "Installer Email" },
	"installer.onlineMonitoringAllowed": { name: "Online Monitoring Allowed", booltype: true },
	"installer.phoneNumber": { name: "Installer Phone" },
	"installer.website": { name: "Installer Website" },
	language: { name: "Language" },
	"last updated": { name: "last updated" },
	lastContact: { name: "Last Contact" },
	lastContactDate: { name: "Last Contact", datetype: true },
	lastupdated: { name: "Last Updated", datetype: true },
	machine: { name: "Machine" },
	master: { name: "Master System", booltype: true },
	"mcu.firmwareVersion": { name: "Firmware Version" },
	"mcu.guiVersion": { name: "GUI Version" },
	"mcu.ipAddress": { name: "MCU IP Address" },
	"mcu.lastContact.severity": { name: "MCU Last Contact Severity" },
	"mcu.lastContact.timestamp": { name: "MCU Last Contact" },
	"mcu.mainControllerSerial": { name: "MCU Serial" },
	"mcu.mainControllerUnitState.name": { name: "System State" },
	"mcu.mainControllerUnitState.operatingMode": { name: "Operating Mode" },
	"mcu.mainControllerUnitState.severity": { name: "System State Severity" },
	mcuOperationalModeId: { name: "MCU Operational Mode ID" },
	"meter.consumption": { name: "House Consumption", unit: "W" },
	"meter.grid_power": { name: "Grid Power", unit: "W" },
	"meter.production": { name: "PV Production", unit: "W" },
	meterReadingVisible: { name: "Meter Reading Visible", booltype: true },
	meterreadingVisible: { name: "Meter Reading Visible", booltype: true },
	mode: { name: "Mode" },
	nachname: { name: "Last Name" },
	name: { name: "System State Name" },
	numberOfWallboxes: { name: "numberOfWallboxes" },
	offpeakVisible: { name: "Off-Peak Visible", booltype: true },
	operatingMode: { name: "Operating Mode" },
	peakShavingCapacityLimitInPercent: { name: "Peak Shaving Capacity Limit", unit: "%" },
	peakShavingEndDate: { name: "Peak Shaving End Date" },
	"peakShavingLocalEndTime.0": { name: "Peak Shaving Local End Hour" },
	"peakShavingLocalEndTime.1": { name: "Peak Shaving Local End Minute" },
	peakShavingMode: { name: "Peak Shaving Mode" },
	peakShavingVisible: { name: "Peak Shaving Visible", booltype: true },
	periodEndDateInMilliseconds: { name: "Data Available Until (ms)", unit: "ms" },
	periodStartDateInMilliseconds: { name: "Data Available From (ms)", unit: "ms" },
	postalCode: { name: "postalCode" },
	"powergenerated.now": { name: "Power Generated (current)", unit: "W" },
	"powergenerated.today": { name: "Power Generated (today)", unit: "kWh" },
	"product.batteryType": { name: "Battery Type" },
	"product.features": { name: "features" },
	"product.generation": { name: "generation" },
	"product.hardwareVariant": { name: "hardwareVariant" },
	"product.name": { name: "name" },
	"product.productFamily": { name: "productFamily" },
	"product.productFamilyName": { name: "productFamilyName" },
	"product.productId": { name: "Product ID" },
	"product.systemType": { name: "System Type" },
	"product.technicalName": { name: "technicalName" },
	produktName: { name: "Product Name" },
	revocationPolicyAccepted: { name: "Revocation Policy Accepted", booltype: true },
	senecBatteryStorageGeneration: { name: "Battery Storage Generation" },
	senecCloudVisible: { name: "SENEC Cloud Visible", booltype: true },
	senecOpenApiVisible: { name: "SENEC Open API Visible", booltype: true },
	serviceVisible: { name: "Service Visible", booltype: true },
	severity: { name: "System State Severity" },
	sgReadyVisible: { name: "SG-Ready Visible", booltype: true },
	since: { name: "Online Since" },
	state: { name: "Online State" },
	statisticDataDownloadVisible: { name: "Statistics Download Visible", booltype: true },
	statusVisible: { name: "Status Visible", booltype: true },
	steckdosenEnabled: { name: "Sockets Enabled", booltype: true },
	steckdosenVisible: { name: "Sockets Visible", booltype: true },
	steckdosennummer: { name: "Socket Number" },
	steckdosenummer: { name: "Socket Number" },
	steuereinheitState: { name: "System State" },
	steuereinheitnummer: { name: "Serial Number" },
	storageDeviceState: { name: "storageDeviceState" },
	street: { name: "street" },
	switchedOn: { name: "Switched On", booltype: true },
	switchedOnToday: { name: "Switched On Today", booltype: true },
	systemId: { name: "systemId" },
	"systemOverview.exchangedSystemId": { name: "Exchanged System ID" },
	"systemOverview.hid": { name: "Hardware ID" },
	"systemOverview.installationDateTime": { name: "Installation Date" },
	"systemOverview.productName": { name: "Product Name" },
	"systemOverview.systemId": { name: "System ID" },
	systemType: { name: "systemType" },
	technischeDatenVisible: { name: "Technical Data Visible", booltype: true },
	timestamp: { name: "timestamp" },
	timezoneText: { name: "timezoneText" },
	"today.batteryChargeInWh": { name: "batteryChargeInWh", unit: "Wh" },
	"today.batteryDischargeInWh": { name: "batteryDischargeInWh", unit: "Wh" },
	"today.batteryLevelInPercent": { name: "batteryLevelInPercent", unit: "%" },
	"today.gridDrawInWh": { name: "gridDrawInWh", unit: "Wh" },
	"today.gridFeedInInWh": { name: "gridFeedInInWh", unit: "Wh" },
	"today.powerConsumptionInWh": { name: "powerConsumptionInWh", unit: "Wh" },
	"today.powerGenerationInWh": { name: "powerGenerationInWh", unit: "Wh" },
	"today.selfSufficiencyInPercent": { name: "selfSufficiencyInPercent", unit: "%" },
	"today.wallboxInWh": { name: "wallboxInWh", unit: "W" },
	valid: { name: "Valid", booltype: true },
	vorname: { name: "First Name" },
	wallboxVisible: { name: "Wallbox Visible", booltype: true },
	"warranty.endDateTime": { name: "Warranty End Date" },
	"warranty.warrantyTermInMonths": { name: "Warranty Term", unit: "months" },
	warrantyAccepted: { name: "Warranty Accepted", booltype: true },
	wartungNotwendig: { name: "Maintenance Required", booltype: true },
	wartungsladungVisible: { name: "Maintenance Charge Visible", booltype: true },
	"wartungsplan.applicable": { name: "Maintenance Applicable", booltype: true },
	"wartungsplan.maintenanceDueSoon": { name: "Maintenance Due Soon", booltype: true },
	"wartungsplan.maintenanceOverdue": { name: "Maintenance Overdue", booltype: true },
	"wartungsplan.minorMaintenancePossible": { name: "Minor Maintenance Possible", booltype: true },
	zoneId: { name: "Timezone" },
	zusatzpaketeVisible: { name: "Additional Packages Visible", booltype: true },
};
