const state_trans = {
	'ENERGY.STAT_STATE.0': {
		0: 'INITIALZUSTAND (0)',
		1: 'KEINE KOMMUNIKATION LADEGERAET (1)',
		2: 'FEHLER LEISTUNGSMESSGERAET (2)',
		3: 'RUNDSTEUEREMPFAENGER (3)',
		4: 'ERSTLADUNG (4)',
		5: 'WARTUNGSLADUNG (5)',
		6: 'WARTUNGSLADUNG FERTIG (6)',
		7: 'WARTUNG NOTWENDIG (7)',
		8: 'MAN. SICHERHEITSLADUNG (8)',
		9: 'SICHERHEITSLADUNG FERTIG (9)',
		10: 'VOLLLADUNG (10)',
		11: 'AUSGLEICHSLADUNG: LADEN (11)',
		12: 'SULFATLADUNG: LADEN (12)',
		13: 'AKKU VOLL (13)',
		14: 'LADEN (14)',
		15: 'AKKU LEER (15)',
		16: 'ENTLADEN (16)',
		17: 'PV + ENTLADEN (17)',
		18: 'NETZ + ENTLADEN (18)',
		19: 'PASSIV (19)',
		20: 'AUSGESCHALTET (20)',
		21: 'EIGENVERBRAUCH (21)',
		22: 'NEUSTART (22)',
		23: 'MAN. AUSGLEICHSLADUNG: LADEN (23)',
		24: 'MAN. SULFATLADUNG: LADEN (24)',
		25: 'SICHERHEITSLADUNG (25)',
		26: 'AKKU-SCHUTZBETRIEB (26)',
		27: 'EG FEHLER (27)',
		28: 'EG LADEN (28)',
		29: 'EG ENTLADEN (29)',
		30: 'EG PASSIV (30)',
		31: 'EG LADEN VERBOTEN (31)',
		32: 'EG ENTLADEN VERBOTEN (32)',
		33: 'NOTLADUNG (33)',
		34: 'SOFTWAREAKTUALISIERUNG (34)',
		35: 'FEHLER: NA-SCHUTZ (35)',
		36: 'FEHLER: NA-SCHUTZ NETZ (36)',
		37: 'FEHLER: NA-SCHUTZ HARDWARE (37)',
		38: 'KEINE SERVERVERBINDUNG (38)',
		39: 'BMS FEHLER (39)',
		40: 'WARTUNG: FILTER (40)',
		41: 'SCHLAFMODUS (41)',
		42: 'WARTE AUF ÜBERSCHUSS (42)',
		43: 'KAPAZITÄTSTEST: LADEN (43)',
		44: 'KAPAZITÄTSTEST: ENTLADEN (44)',
		45: 'MAN. SULFATLADUNG: WARTEN (45)',
		46: 'MAN. SULFATLADUNG: FERTIG (46)',
		47: 'MAN. SULFATLADUNG: FEHLER (47)',
		48: 'AUSGLEICHSLADUNG: WARTEN (48)',
		49: 'NOTLADUNG: FEHLER (49)',
		50: 'MAN: AUSGLEICHSLADUNG: WARTEN (50)',
		51: 'MAN: AUSGLEICHSLADUNG: FEHLER (51)',
		52: 'MAN: AUSGLEICHSLADUNG: FERTIG (52)',
		53: 'AUTO: SULFATLADUNG: WARTEN (53)',
		54: 'LADESCHLUSSPHASE (54)',
		55: 'BATTERIETRENNSCHALTER AUS (55)',
		56: 'PEAK-SHAVING: WARTEN (56)',
		57: 'FEHLER LADEGERAET (57)',
		58: 'NPU-FEHLER (58)',
		59: 'BMS OFFLINE (59)',
		60: 'WARTUNGSLADUNG FEHLER (60)',
		61: 'MAN. SICHERHEITSLADUNG FEHLER (61)',
		62: 'SICHERHEITSLADUNG FEHLER (62)',
		63: 'KEINE MASTERVERBINDUNG (63)',
		64: 'LITHIUM SICHERHEITSMODUS AKTIV (64)',
		65: 'LITHIUM SICHERHEITSMODUS BEENDET (65)',
		66: 'FEHLER BATTERIESPANNUNG (66)',
		67: 'BMS DC AUSGESCHALTET (67)',
		68: 'NETZINITIALISIERUNG (68)',
		69: 'NETZSTABILISIERUNG (69)',
		70: 'FERNABSCHALTUNG (70)',
		71: 'OFFPEAK-LADEN (71)',
		72: 'FEHLER HALBBRÜCKE (72)',
		73: 'BMS: FEHLER BETRIEBSTEMPERATUR (73)',
		74: 'FACOTRY SETTINGS NICHT GEFUNDEN (74)',
		75: 'NETZERSATZBETRIEB (75)',
		76: 'NETZERSATZBETRIEB AKKU LEER (76)',
		77: 'NETZERSATZBETRIEB FEHLER (77)',
		78: 'INITIALISIERUNG (78)',
		79: 'INSTALLATIONSMODUS (79)',
		80: 'NETZAUSFALL (80)',
		81: 'BMS UPDATE ERFORDERLICH (81)',
		82: 'BMS KONFIGURATION ERFORDERLICH (82)',
		83: 'ISOLATIONSTEST (83)',
		84: 'SELBSTTEST (84)',
		85: 'EXTERNE STEUERUNG (85)',
		86: 'TEMPERATUR SENSOR FEHLER (86)',
		87: 'NETZBETREIBER: LADEN GESPERRT (87)',
		88: 'NETZBETREIBER: ENTLADEN GESPERRT (88)',
		89: 'RESERVEKAPAZITÄT (89)',
		90: 'SELBSTTEST FEHLER (90)',
		91: 'ISOLATIONSFEHLER (91)',
		92: 'PV-MODUS (92)',
		93: 'FERNABSCHALTUNG NETZBETREIBER (93)',
		94: 'FEHLER DRM0 (94)',
		95: 'BATTERIEDIAGNOSE (95)',
		96: 'BATTERIE BALANCIERUNG (96)',
		97: 'SICHERHEITSENTLADUNG (97)',
		98: 'BMS FEHLER - MODULUNGLEICHGEWICHT',
		99: 'AUFWACHLADUNG (99)'
	},
	'ENERGY_STAT_STATE.1': {
		0: 'INITIALSTATE',
		1: 'ERROR INVERTER COMMUNICATION',
		2: 'ERROR ELECTRICY METER',
		3: 'RIPPLE CONTROL RECEIVER',
		4: 'INITIAL CHARGE',
		5: 'MAINTENANCE CHARGE',
		6: 'MAINTENANCE READY',
		7: 'MAINTENANCE REQUIRED',
		8: 'MAN. SAFETY CHARGE',
		9: 'SAFETY CHARGE READY',
		10: 'FULL CHARGE',
		11: 'EQUALIZATION: CHARGE',
		12: 'DESULFATATION: CHARGE',
		13: 'BATTERY FULL',
		14: 'CHARGE',
		15: 'BATTERY EMPTY',
		16: 'DISCHARGE',
		17: 'PV + DISCHARGE',
		18: 'GRID + DISCHARGE',
		19: 'PASSIVE',
		20: 'OFF',
		21: 'OWN CONSUMPTION',
		22: 'RESTART',
		23: 'MAN. EQUALIZATION: CHARGE',
		24: 'MAN. DESULFATATION: CHARGE',
		25: 'SAFETY CHARGE',
		26: 'BATTERY PROTECTION MODE',
		27: 'EG ERROR',
		28: 'EG CHARGE',
		29: 'EG DISCHARGE',
		30: 'EG PASSIVE',
		31: 'EG PROHIBIT CHARGE',
		32: 'EG PROHIBIT DISCHARGE',
		33: 'EMERGANCY CHARGE',
		34: 'SOFTWARE UPDATE',
		35: 'NSP ERROR',
		36: 'NSP ERROR: GRID',
		37: 'NSP ERROR: HARDWRE',
		38: 'NO SERVER CONNECTION',
		39: 'BMS ERROR',
		40: 'MAINTENANCE: FILTER',
		41: 'SLEEPING MODE',
		42: 'WAITING EXCESS',
		43: 'CAPACITY TEST: CHARGE',
		44: 'CAPACITY TEST: DISCHARGE',
		45: 'MAN. DESULFATATION: WAIT',
		46: 'MAN. DESULFATATION: READY',
		47: 'MAN. DESULFATATION: ERROR',
		48: 'EQUALIZATION: WAIT',
		49: 'EMERGANCY CHARGE: ERROR',
		50: 'MAN. EQUALIZATION: WAIT',
		51: 'MAN. EQUALIZATION: ERROR',
		52: 'MAN: EQUALIZATION: READY',
		53: 'AUTO. DESULFATATION: WAIT',
		54: 'ABSORPTION PHASE',
		55: 'DC-SWITCH OFF',
		56: 'PEAK-SHAVING: WAIT',
		57: 'ERROR BATTERY INVERTER',
		58: 'NPU-ERROR',
		59: 'BMS OFFLINE',
		60: 'MAINTENANCE CHARGE ERROR',
		61: 'MAN. SAFETY CHARGE ERROR',
		62: 'SAFETY CHARGE ERROR',
		63: 'NO CONNECTION TO MASTER',
		64: 'LITHIUM SAFE MODE ACTIVE',
		65: 'LITHIUM SAFE MODE DONE',
		66: 'BATTERY VOLTAGE ERROR',
		67: 'BMS DC SWITCHED OFF',
		68: 'GRID INITIALIZATION',
		69: 'GRID STABILIZATION',
		70: 'REMOTE SHUTDOWN',
		71: 'OFFPEAK-CHARGE',
		72: 'ERROR HALFBRIDGE',
		73: 'BMS: ERROR OPERATING TEMPERATURE',
		74: 'FACOTRY SETTINGS NOT FOUND',
		75: 'BACKUP POWER MODE - ACTIVE',
		76: 'BACKUP POWER MODE - BATTERY EMPTY',
		77: 'BACKUP POWER MODE ERROR',
		78: 'INITIALISING',
		79: 'INSTALLATION MODE',
		80: 'GRID OFFLINE',
		81: 'BMS UPDATE NEEDED',
		82: 'BMS CONFIGURATION NEEDED',
		83: 'INSULATION TEST',
		84: 'SELFTEST',
		85: 'EXTERNAL CONTROL',
		86: 'ERROR: TEMPERATURESENSOR',
		87: 'GRID OPERATOR: CHARGE PROHIBITED',
		88: 'GRID OPERATOR: DISCHARGE PROHIBITED',
		89: 'SPARE CAPACITY',
		90: 'SELFTEST ERROR',
		91: 'EARTH FAULT',
		92: 'PV-MODE',
		93: 'REMOTE SHUTDOWN GRID OPERATOR',
		94: 'ERROR DRM0 (94)',
		95: 'BATTERY DIAGNOSIS (95)',
		96: 'BATTERY BALANCING (96)',
		97: 'SAFETY DISCHARGE (97)',
		98: 'BMS ERROR - MODULE IMBALANCE',
		99: 'WAKE UP CHARGING (99)'
	},
	'ENERGY_STAT_STATE.2': {
		0: 'STATO INIZIALE',
		1: 'ERRORE COMMUNICAZIONE INVERTER',
		2: 'ERRORE WATTMETRO',
		3: 'RICEVITORE RIPPLE CONTROL',
		4: 'PRIMA CARICA',
		5: 'CARICA DI MANTENIMENTO',
		6: 'CARICA DI MANTENIMENTO COMPLETATA',
		7: 'MANUTENZIONE: NECESSARIA',
		8: 'CARICA DI SICUREZZA MANUALE',
		9: 'CARICA DI SICUREZZA COMPLETA',
		10: 'CARICA COMPLETA',
		11: 'CARICA DI EQUALIZZAZIONE',
		12: 'CARICA DI DESOLFATAZIONE',
		13: 'ACCUMULATORE CARICO',
		14: 'CARICA',
		15: 'ACCUMULATORE SCARICO',
		16: 'SCARICA',
		17: 'FV + SCARICA',
		18: 'RETE + SCARICA',
		19: 'PASSIVO',
		20: 'SPENTO',
		21: 'AUTOCONSUMO',
		22: 'RIAVVIO',
		23: 'CARICA DI EQUALIZZAZIONE MANUALE',
		24: 'CARICA DI DESOLFATAZIONE MANUALE',
		25: 'CARICA DI SICUREZZA',
		26: 'MODALITÀ PROTEZIONE ACCUMULATORE',
		27: 'ERRORE EG',
		28: 'EG: CARICA',
		29: 'EG: SCARICA',
		30: 'EG: PASSIVO',
		31: 'CARICA EG PROIBITA',
		32: 'SCARICAMENTO EG PROIBITO',
		33: 'CARICA D\'EMERGENZA',
		34: 'AGGIORNAMENTO SOFTWARE',
		35: 'ERRORE SPI',
		36: 'ERRORE SPI: RETE ',
		37: 'ERRORE SPI: HARDWARE ',
		38: 'NESSUNA CONNESSIONE AL SERVER',
		39: 'ERRORE BMS',
		40: 'SOSTITUZIONE DEL FILTRO NECESSARIA',
		41: 'BATTERIA AL LITIO SPENTA',
		42: 'IN ATTESA DI SURPLUS ENERGETICO',
		43: 'TEST DI CAPACITÀ: CARICA',
		44: 'TEST DI CAPACITÀ: SCARICA',
		45: 'CARICA DI DESOLFATAZIONE MANUALE: ATTESA',
		46: 'CARICA DI DESOLFATAZIONE MANUALE: COMPLETA',
		47: 'CARICA DI DESOLFATAZIONE MANUALE: ERRORE',
		48: 'EQUALIZZAZIONE: ATTESA',
		49: 'CARICA D\'EMERGENZA: ERRORE',
		50: 'EQUALIZZAZIONE MANUALE: ATTESA',
		51: 'EQUALIZZAZIONE MANUALE: ERRORE',
		52: 'EQUALIZZAZIONE MANUALE: COMPLETA',
		53: 'CARICA DI DESOLFATAZIONE: ATTESA',
		54: 'FASE FINALE CARICA',
		55: 'SEZIONATORE BATTERIA OFF',
		56: 'PEAK SHAVING: ATTESA',
		57: 'ERRORE DISPOSITIVO DI CARICA',
		58: 'ERRORE NPU',
		59: 'BMS DISCONESSO',
		60: 'CARICA DI MANUTENZIONE ERRORE',
		61: 'CARICA DI SICUREZZA MANUALE ERRORE',
		62: 'CARICA DI SICUREZZA ERRORE',
		63: 'NESSUNA CONNESSIONE MASTER',
		64: 'MODALITA DI PROTEZIONE LITIO ATTIVA',
		65: 'MODALITA DI PROTEZIONE LITIO COMPLETA',
		66: 'ERORE DI TENSIONE BATTERIA',
		67: 'BMS DC SPENTO',
		68: 'INIZIALIZZAZIONE DELLA RETE',
		69: 'STABILIZZAZIONE DELLA RETE',
		70: 'ARRESTO REMOTO',
		71: 'OFFPEAK-CARICA',
		72: 'ERRORE MEZZO PONTE',
		73: 'BMS: ERRORE TEMPERATURA DI FUNZIONAMENTO',
		74: 'FACOTRY SETTINGS NON TROVATO',
		75: 'FUNZIONAMENTO ISOLATO',
		76: 'FUNZIONAMENTO ISOLATO ACCUMULATORE SCARICO',
		77: 'ERORE DI FUNZIONAMENTO ISOLATO',
		78: 'INIZIALIZZAZIONE',
		79: 'MODALITA INSTALLAZIONE',
		80: 'RETE OFFLINE',
		81: 'AGGIORNAMENTO BMS NECESSARIO',
		82: 'CONFIGURAZIONE BMS NECESSARIA',
		83: 'TEST DI ISOLAMENTO',
		84: 'AUTOTEST',
		85: 'CONTROLLO ESTERNO',
		86: 'ERRORE SENSORE DI TEMPERATURA',
		87: 'OPERATORE DI RETE: CARICA BLOCCATA',
		88: 'OPERATORE DI RETE: SCARICA BLOCCATA',
		89: 'CAPACITA INUTILIZZATA',
		90: 'ERRORE DI AUTOTEST',
		91: 'FAGLIA TERRESTRE',
		92: 'MODALITÀ FOTOVOLTAICA',
		93: 'SPEGNIMENTO A DISTANZA OPERATORE DI RETE',
		94: 'ERRORE DRM0',
		95: 'DIAGNOSI DELLA BATTERIA (95)',
		96: 'BILANCIAMENTO DELLA BATTERIA (96)',
		97: 'SCARICO DI SICUREZZA (97)',
		98: 'ERRORE BMS - SQUILIBRIO DEL MODULOTRANSLATE',
		99: 'CARICA DI RISVEGLIO (99)'
	},
	'FACTORY.BAT_TYPE.0' : {
		0: 'Studer Xtender (0)',
		1: 'SenecBatt (1)',
		2: 'Senec Inverter V2 (2)',
		3: 'SENEC.Inverter V2.1 (3)',
		4: 'SENEC.Inverter V3 LV (4)'
	},
	'FACTORY.BAT_TYPE.1' : {
		0: 'Studer Xtender (0)',
		1: 'SenecBatt (1)',
		2: 'Senec Inverter V2 (2)',
		3: 'SENEC.Inverter V2.1 (3)',
		4: 'SENEC.Inverter V3 LV (4)'
	},
	'FACTORY.BAT_TYPE.2' : {
		0: 'Studer Xtender (0)',
		1: 'SenecBatt (1)',
		2: 'Senec Inverter V2 (2)',
		3: 'SENEC.Inverter V2.1 (3)',
		4: 'SENEC.Inverter V3 LV (4)'
	},
	'FACTORY.COUNTRY.0' : {
		0: 'Deutschland - DE (0)',
		1: 'Italien - IT (1)',
		2: 'Australien - AU (2)',
		3: 'Österreich - AT (3)'
	},
	'FACTORY.COUNTRY.1' : {
		0: 'Germany - DE (0)',
		1: 'Italy - IT (1)',
		2: 'Australia - AU (2)',
		3: 'Austria - AT (3)'
	},
	'FACTORY.COUNTRY.3' : {
		0: 'Germania - DE (0)',
		1: 'Italia - IT (1)',
		2: 'Australia - AU (2)',
		3: 'Austria - AT (3)'
	},
	'FACTORY.SYS_TYPE.0' : {
		0: 'Senec Home 8.0 / Blei (0)',
		1: 'Senec Business 30.0 / Blei (1)',
		2: 'Solarinvert Storage 10.0 / Blei (2)',
		3: 'Senec Home 4.0 / Blei (3)',
		4: 'Senec Home 5.0/7.5/10.0 / Lithium (4)',
		5: 'Senec Home 15.0 / Lithium (5)',
		6: 'Senec Business 25.0 / Lithium (6)',
		7: 'Senec Home 6.0 Pb (7)',
		8: 'Senec Home 10.0 Pb (8)',
		9: 'Senec Home V2 5.0/7.5/10.0 (9)',
		10: 'Senec Business V2 30.0 / Blei (10)',
		11: 'Senec Home V2 10.0 / Blei (11)',
		12: 'OEM LG (12)',
		13: 'Senec Business V2_2ph / Lithium (13)',
		14: 'Senec Business V2 3ph / Lithium (14)',
		15: 'Senec Home V2.1 1ph / Lithium (15)',
		16: 'ADS Tec (16)',
		17: 'Senec.Home V3 Hybrid (17)',
		18: 'Senec.Home V3 Hybrid duo (18)',
		19: 'Senec.Home V3 Hybrid (19)'
	},
	'FACTORY.SYS_TYPE.1' : {
		0: 'Senec Home 8.0 / Blei (0)',
		1: 'Senec Business 30.0 / Blei (1)',
		2: 'Solarinvert Storage 10.0 / Blei (2)',
		3: 'Senec Home 4.0 / Blei (3)',
		4: 'Senec Home 5.0/7.5/10.0 / Lithium (4)',
		5: 'Senec Home 15.0 / Lithium (5)',
		6: 'Senec Business 25.0 / Lithium (6)',
		7: 'Senec Home 6.0 Pb (7)',
		8: 'Senec Home 10.0 Pb (8)',
		9: 'Senec Home V2 5.0/7.5/10.0 (9)',
		10: 'Senec Business V2 30.0 / Blei (10)',
		11: 'Senec Home V2 10.0 / Blei (11)',
		12: 'OEM LG (12)',
		13: 'Senec Business V2_2ph / Lithium (13)',
		14: 'Senec Business V2 3ph / Lithium (14)',
		15: 'Senec Home V2.1 1ph / Lithium (15)',
		16: 'ADS Tec (16)',
		17: 'Senec.Home V3 Hybrid (17)',
		18: 'Senec.Home V3 Hybrid duo (18)',
		19: 'Senec.Home V3 Hybrid (19)'
	},
	'FACTORY.SYS_TYPE.2' : {
		0: 'Senec Home 8.0 / Blei (0)',
		1: 'Senec Business 30.0 / Blei (1)',
		2: 'Solarinvert Storage 10.0 / Blei (2)',
		3: 'Senec Home 4.0 / Blei (3)',
		4: 'Senec Home 5.0/7.5/10.0 / Lithium (4)',
		5: 'Senec Home 15.0 / Lithium (5)',
		6: 'Senec Business 25.0 / Lithium (6)',
		7: 'Senec Home 6.0 Pb (7)',
		8: 'Senec Home 10.0 Pb (8)',
		9: 'Senec Home V2 5.0/7.5/10.0 (9)',
		10: 'Senec Business V2 30.0 / Blei (10)',
		11: 'Senec Home V2 10.0 / Blei (11)',
		12: 'OEM LG (12)',
		13: 'Senec Business V2_2ph / Lithium (13)',
		14: 'Senec Business V2 3ph / Lithium (14)',
		15: 'Senec Home V2.1 1ph / Lithium (15)',
		16: 'ADS Tec (16)',
		17: 'Senec.Home V3 Hybrid (17)',
		18: 'Senec.Home V3 Hybrid duo (18)',
		19: 'Senec.Home V3 Hybrid (19)'
	},
	'WALLBOX.STATE.0' : {
		161: 'Warte auf E-Fahrzeug (161)',
		177: 'E-Fahrzeug fragt Ladung an (177)',
		178: 'E-Fahrzeug kann geladen werden (178)',
		194: 'E-Fahrzeug lädt momentan (194)',
		195: 'E-Fahrzeug lädt mit verringertem Strom (Fehler F16, F17) (195)',
		196: 'E-Fahrzeug lädt mit verringertem Strom (Schieflast F15) (196)',
		224: 'Wallbox deaktiviert durch EN1/Schlüsselschalter oder für Konfigurationsupdate (224)',
		225: 'Test Production (225)',
		226: 'Steuereinheit kann programmiert werden (226)',
		227: 'Warte auf Kommunikation mit SENEC-Speicher (227)',
		241: 'Unerwartet geschlossener Kontakt (verschweißt) (241)',
		242: 'Interner Fehler (242)',
		243: 'DC Fehlerstrom erkannt (243)',
		244: 'Fehler Kommunikation (244)',
		245: 'Sperren der Ladebuchse fehlgeschlagen (245)',
		246: 'Kabelfehler (246)',
		247: 'E-Fahrzeug meldet Übertemperatur (247)',
		248: 'Kommunikationsfehler zum E-Fahrzeug (248)',
		249: 'Überstrom erkannt (249)',
		250: 'Temperaturgrenzwert überschritten (250)',
		251: 'Unerwartet geöffneter Kontakt (251)',
		252: 'Reserved State (252)',
		253: 'Reserved State (253)'
	},
	'WALLBOX.STATE.1' : {
		161: 'Waiting for EV',
		177: 'EV is asking for charging',
		178: 'EV has the permission to charge',
		194: 'EV is charged',
		195: 'C2 w. reduced current (error F16, F17)',
		196: 'C2 w. reduced current (imbalance F15)',
		224: 'Charging point disabled by enable input EN1 / key lock or for update',
		225: 'production test',
		226: 'EVCC can be programmed',
		227: 'Bus idle',
		241: 'Unintended closed contact (Welding)',
		242: 'Internal error',
		243: 'DC residual current detected',
		244: 'Upstream communication timeout',
		245: 'Lock of socket failed',
		246: 'CS out of range',
		247: 'State D requested by EV',
		248: 'CP out of range',
		249: 'Overcurrent detected',
		250: 'Temperature outside limits',
		251: 'Unintended opened contact',
		252: 'Reserved State',
		253: 'Reserved State'
	},
	'WALLBOX.STATE.2' : {
		161: 'In attesa di collegamento ad EV',
		177: 'Richiesta carica da auto elettrica',
		178: 'L\'auto elettrica è pronta per la ricarica',
		194: 'L\'auto elettrica è in carica',
		195: 'Carica auto elettrica a corrente ridotta',
		196: 'Carica auto elettrica a corrente ridotta',
		224: 'Wallbox disattivato dal EN1 / interruttore a chiave o per aggiornamento',
		225: 'Test',
		226: 'L\'unità di controllo può essere programmata',
		227: 'Attendere la comunicazione con il sistema di accumulo SENEC',
		241: 'Errore: Contatto chiuso (saldato)',
		242: 'Errore interno',
		243: 'Rilevata corrente di guasto DC',
		244: 'Errore connessione',
		245: 'Blocco della presa per la ricarica non riuscito',
		246: 'Guasto del cavo',
		247: 'Segnalazione sovratemperatura',
		248: 'Errore di comunicazione con l\'auto elettrica',
		249: 'Rilevata sovracorrente',
		250: 'Errore: Temperature limite superate!',
		251: 'Errore: Contatto aperto',
		252: 'Reserved State',
		253: 'Reserved State',
	}

}

module.exports = state_trans;
