/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "SENEC adapter settings": {
        "en": "SENEC adapter settings",
        "de": "SENEC-Adaptereinstellungen",
        "ru": "Настройки адаптера SENEC",
        "pt": "Configurações do adaptador SENEC",
        "nl": "SENEC-adapterinstellingen",
        "fr": "Paramètres de l'adaptateur SENEC",
        "it": "Impostazioni dell'adattatore SENEC",
        "es": "Configuración del adaptador SENEC",
        "pl": "Ustawienia adaptera SENEC",
        "zh-cn": "SENEC适配器设置"
    },
    "IP / FQDN of SENEC System": {
        "en": "IP / FQDN of SENEC System",
        "de": "IP / FQDN des SENEC-Systems",
        "ru": "IP / FQDN системы SENEC",
        "pt": "IP / FQDN do sistema SENEC",
        "nl": "IP / FQDN van SENEC-systeem",
        "fr": "IP / FQDN du système SENEC",
        "it": "IP / FQDN del sistema SENEC",
        "es": "IP / FQDN del sistema SENEC",
        "pl": "Adres IP / FQDN systemu SENEC",
        "zh-cn": "SENEC系统的IP / FQDN"
    },
    "pollRateHigh": {
		"en": "Polling Interval (seconds) High Priority Data",
		"de": "Abfrageintervall (Sekunden) Daten mit hoher Priorität",
		"ru": "Интервал опроса (секунды) Данные с высоким приоритетом",
		"pt": "Intervalo de pesquisa (segundos) Dados de alta prioridade",
		"nl": "Polling Interval (seconden) Gegevens met hoge prioriteit",
		"fr": "Intervalle d'interrogation (secondes) Données de haute priorité",
		"it": "Intervallo di polling (secondi) Dati ad alta priorità",
		"es": "Intervalo de sondeo (segundos) Datos de alta prioridad",
		"pl": "Interwał odpytywania (sekundy) Dane o wysokim priorytecie",
		"zh-cn": "轮询间隔（秒）高优先级数据"
    },
	"pollRateHighTooltip": {
		"en": "Here you can define the polling interval [min 1, max 3600 seconds]. Default = 10.",
		"de": "Hier können Sie das Abfrageintervall definieren [min 1, max 3600 Sekunden]. Standard = 10.",
		"ru": "Здесь вы можете определить интервал опроса [мин 1, макс 3600 секунд]. По умолчанию = 10.",
		"pt": "Aqui você pode definir o intervalo de pesquisa [min 1, max 3600 segundos]. Padrão = 10.",
		"nl": "Hier kunt u het polling-interval definiëren [min 1, max 3600 seconden]. Standaard = 10.",
		"fr": "Ici, vous pouvez définir l'intervalle d'interrogation [min 1, max 3600 secondes]. Par défaut = 10.",
		"it": "Qui è possibile definire l'intervallo di polling [min 1, max 3600 secondi]. Predefinito = 10.",
		"es": "Aquí puede definir el intervalo de sondeo [mínimo 1, máximo 3600 segundos]. Por defecto = 10.",
		"pl": "Tutaj możesz zdefiniować interwał odpytywania [min 1, max 3600 sekund]. Domyślnie = 10.",
		"zh-cn": "在这里，您可以定义轮询间隔[最小1，最大3600秒]。默认值= 10。"
	},
    "pollRateLow": {
		"en": "Polling Interval (minutes) Low Priority Data",
		"de": "Abfrageintervall (Minuten) Daten mit niedriger Priorität",
		"ru": "Интервал опроса (минуты) Данные с низким приоритетом",
		"pt": "Intervalo de pesquisa (minutos) Dados de baixa prioridade",
		"nl": "Polling Interval (minuten) Gegevens met lage prioriteit",
		"fr": "Intervalle d'interrogation (minutes) Données de faible priorité",
		"it": "Intervallo di polling (minuti) Dati a bassa priorità",
		"es": "Intervalo de sondeo (minutos) Datos de baja prioridad",
		"pl": "Interwał odpytywania (minuty) Dane o niskim priorytecie",
		"zh-cn": "轮询间隔（分钟）低优先级数据"
    },
	"pollRateLowTooltip": {
		"en": "Here you can define the polling interval for low priority data [min 60, max 3600 minutes]. Default = 60.",
		"de": "Hier können Sie das Abfrageintervall für Daten mit niedriger Priorität definieren [min 60, max 3600 Minuten]. Standard = 60.",
		"ru": "Здесь вы можете определить интервал опроса для данных с низким приоритетом [мин 60, макс 3600 минут]. По умолчанию = 60.",
		"pt": "Aqui você pode definir o intervalo de pesquisa para dados de baixa prioridade [min 60, max 3600 minutos]. Padrão = 60.",
		"nl": "Hier kunt u het polling-interval definiëren voor gegevens met een lage prioriteit [min 60, max 3600 minuten]. Standaard = 60.",
		"fr": "Ici, vous pouvez définir l'intervalle d'interrogation pour les données de faible priorité [min 60, max 3600 minutes]. Par défaut = 60.",
		"it": "Qui è possibile definire l'intervallo di polling per i dati a bassa priorità [min 60, max 3600 minuti]. Predefinito = 60.",
		"es": "Aquí puede definir el intervalo de sondeo para datos de baja prioridad [mínimo 60, máximo 3600 minutos]. Por defecto = 60.",
		"pl": "Tutaj możesz zdefiniować interwał odpytywania dla danych o niskim priorytecie [min 60, max 3600 minut]. Domyślnie = 60.",
		"zh-cn": "在这里，您可以定义低优先级数据的轮询间隔[最小60，最大3600分钟]。默认值= 60"
	},
	"iptooltip": {
		"en": "Here you enter the IP or FQDN of your SENEC System",
		"de": "Hier geben Sie die IP oder FQDN Ihres SENEC-Systems ein",
		"ru": "Здесь вы вводите IP или полное доменное имя вашей системы SENEC",
		"pt": "Aqui você digita o IP ou FQDN do seu sistema SENEC",
		"nl": "Hier voert u de IP of FQDN van uw SENEC-systeem in",
		"fr": "Ici, vous entrez l'IP ou le FQDN de votre système SENEC",
		"it": "Qui inserisci l'IP o il nome FQDN del tuo sistema SENEC",
		"es": "Aquí ingresa la IP o FQDN de su sistema SENEC",
		"pl": "Tutaj wprowadź adres IP lub nazwę FQDN swojego systemu SENEC",
		"zh-cn": "在这里输入SENEC系统的IP或FQDN"
	},
	"pollRetry": {
		"en": "Polling Retries",
		"de": "Wiederholungsversuche",
		"ru": "Повторные попытки",
		"pt": "Tentativas de sondagem",
		"nl": "Polling pogingen",
		"fr": "Relance des interrogations",
		"it": "Tentativi di polling",
		"es": "Reintentos de sondeo",
		"pl": "Ponawia próbę odpytywania",
		"zh-cn": "轮询重试"
	},
    "pollRetryTooltip": {
		"en": "Here you enter how often you want the adapter to retry polling in case of error [min 0, max 999]. 0 = never, 999 = unlimited. Default = 10.",
		"de": "Hier geben Sie an, wie oft der Adapter im Fehlerfall die Abfrage wiederholen soll [min 0, max 999]. 0 = nie, 999 = unbegrenzt. Standard = 10.",
		"ru": "Здесь вы вводите, как часто вы хотите, чтобы адаптер повторил опрос в случае ошибки [min 0, max 999]. 0 = никогда, 999 = неограниченно. По умолчанию = 10.",
		"pt": "Aqui, você insere com que frequência deseja que o adaptador tente novamente a pesquisa em caso de erro [min 0, máximo 999]. 0 = nunca, 999 = ilimitado. Padrão = 10.",
		"nl": "Hier geeft u op hoe vaak u wilt dat de adapter polling opnieuw probeert in geval van een fout [min 0, max 999]. 0 = nooit, 999 = onbeperkt. Standaard = 10.",
		"fr": "Vous saisissez ici la fréquence à laquelle vous souhaitez que l'adaptateur relance l'interrogation en cas d'erreur [min 0, max 999]. 0 = jamais, 999 = illimité. Par défaut = 10.",
		"it": "Qui inserisci la frequenza con cui desideri che l'adattatore riprova a eseguire il polling in caso di errore [min 0, max 999]. 0 = mai, 999 = illimitato. Predefinito = 10.",
		"es": "Aquí ingresa con qué frecuencia desea que el adaptador vuelva a intentar el sondeo en caso de error [min 0, max 999]. 0 = nunca, 999 = ilimitado. Por defecto = 10.",
		"pl": "Tutaj wprowadź, jak często adapter ma ponawiać próbę odpytywania w przypadku błędu [min. 0, maks. 999]. 0 = nigdy, 999 = nieograniczony. Domyślnie = 10.",
		"zh-cn": "在此输入发生错误[最小0，最大999]时适配器重试轮询的频率。 0 =永不，999 =无限。默认值= 10。"
	},
    "pollRetryFac": {
		"en": "Polling Retry Factor",
		"de": "Polling-Wiederholungsfaktor",
		"ru": "Коэффициент повтора опроса",
		"pt": "Fator de Nova Tentativa de Pesquisa",
		"nl": "Polling Retry Factor",
		"fr": "Facteur de nouvelle tentative d'interrogation",
		"it": "Fattore di tentativo di polling",
		"es": "Factor de reintento de sondeo",
		"pl": "Współczynnik ponownej próbkowania",
		"zh-cn": "轮询重试因子"
	},
    "pollRetryFacToolip": {
		"en": "Here you enter how you want to space retries apart of each other. n'th retry will happen after Interval * Multiplier * n seconds. [min 1, max 10]. Default = 2.",
		"de": "Hier geben Sie ein, wie sich der zeitliche Abstand zwischen den Wiederholungsversuchen verhält. Der n-te Wiederholungsversuch erfolgt nach Intervall * Multiplikator * n Sekunden. [min 1, max 10]. Standard = 2. ",
		"ru": "Здесь вы вводите, как вы хотите, чтобы интервалы повторялись друг от друга. n-я повторная попытка произойдет через интервал *множитель* n секунд. [мин 1, макс 10]. По умолчанию = 2. ",
		"pt": "Aqui você digita como deseja espaçar as tentativas uma da outra. a enésima nova tentativa ocorrerá após o Intervalo *Multiplicador* n segundos. [min 1, max 10]. Padrão = 2. ",
		"nl": "Hier geeft u op hoe u pogingen uit elkaar wilt plaatsen. de nieuwe poging zal gebeuren na Interval *Multiplier* n seconden. [min 1, max 10]. Standaard = 2. ",
		"fr": "Vous saisissez ici comment vous souhaitez espacer les tentatives les unes des autres. La sixième tentative ne se produira qu'après Intervalle *Multiplicateur* n secondes. [min 1, max 10]. Par défaut = 2. ",
		"it": "Qui si inserisce il modo in cui si desidera separare i tentativi uno dall'altro. l'ennesimo tentativo avverrà dopo l'intervallo *moltiplicatore* n secondi. [min 1, max 10]. Predefinito = 2. ",
		"es": "Aquí ingresa cómo desea espaciar los reintentos uno del otro. el enésimo reintento ocurrirá después del Intervalo *Multiplicador* n segundos. [mínimo 1, máximo 10]. Por defecto = 2. ",
		"pl": "Tutaj podajesz, w jaki sposób chcesz umieścić odstępy między sobą. n-ta próba nastąpi po przerwie *Mnożnik* n sekund. [min 1, maks. 10]. Domyślnie = 2. ",
		"zh-cn": "在这里，您可以输入相互重试间隔的方式。第n次重试将在间隔*乘数* n秒后发生。 [最小1，最大10]。默认值= 2。"
	},
    "pollTimeOut": {
		"en": "Request-Timeout (ms)",
		"de": "Request-Timeout (ms)",
		"ru": "Время ожидания запроса (мс)",
		"pt": "Tempo limite da solicitação (ms)",
		"nl": "Verzoek-time-out (ms)",
		"fr": "Délai d'expiration de la demande (ms)",
		"it": "Request-Timeout (ms)",
		"es": "Solicitud de tiempo de espera (ms)",
		"pl": "Limit czasu żądania (ms)",
		"zh-cn": "请求超时（毫秒）"
	},
    "pollTimeOutToolip": {
		"en": "Here you define the request timeout when polling from SENEC [min 1000, max 100000]. Default = 5000.",
		"de": "Hier definieren Sie das Anforderungszeitlimit beim Abrufen von SENEC [min 1000, max 100000]. Standard = 5000.",
		"ru": "Здесь вы определяете время ожидания запроса при опросе от SENEC [min 1000, max 100000]. По умолчанию = 5000.",
		"pt": "Aqui você define o tempo limite da solicitação ao pesquisar no SENEC [min 1000, max 100000]. Padrão = 5000.",
		"nl": "Hier definieert u de time-out van het verzoek bij polling vanuit SENEC [min 1000, max 100000]. Standaard = 5000.",
		"fr": "Vous définissez ici le délai d'expiration de la requête lors de l'interrogation à partir de SENEC [min 1000, max 100000]. Par défaut = 5000.",
		"it": "Qui si definisce il timeout della richiesta durante il polling da SENEC [min 1000, max 100000]. Predefinito = 5000.",
		"es": "Aquí define el tiempo de espera de la solicitud al sondear desde SENEC [min 1000, max 100000]. Por defecto = 5000.",
		"pl": "Tutaj definiujesz limit czasu żądania podczas odpytywania z SENEC [min 1000, max 100000]. Domyślnie = 5000.",
		"zh-cn": "在此定义从SENEC进行轮询时的请求超时[最小1000，最大100000]。默认值= 5000"
	},
	"prioIntro": {
		"en": "Here you can change polling priority for specific datapoints. Leave fields empty to use default values.<br>To add additional datapoints enter them commaseparated without any extra blanks.<br>There will be NO plausibility checks done! If adapter doesn't work after your changes, check your input.<br><b><u><i>WARNING! Adding datapoints for high priority polling can negatively affect your SENEC appliance! Adverse effects are your responsibility when using this adapter.</i></u></b>",
		"de": "Hier können Sie die Polling-Priorität für bestimmte Datenpunkte ändern. Lassen Sie die Felder leer, um Standardwerte zu verwenden.<br> Um zusätzliche Datenpunkte hinzuzufügen, geben Sie diese durch Kommas getrennt ohne zusätzliche Leerzeichen ein.<br> Es werden KEINE Plausibilitätsprüfungen durchgeführt! Wenn der Adapter nach Ihren Änderungen nicht funktioniert, überprüfen Sie Ihre Eingabe.<br> <b><u><i>WARNUNG! Das Hinzufügen von Datenpunkten für Polling mit hoher Priorität kann sich negativ auf Ihre SENEC-Appliance auswirken! Bei Verwendung dieses Adapters sind Sie für Nebenwirkungen verantwortlich.</i></u></b>",
		"ru": "Здесь вы можете изменить приоритет опроса для определенных точек данных. Оставьте поля пустыми, чтобы использовать значения по умолчанию.<br> Чтобы добавить дополнительные точки данных, введите их через запятую без дополнительных пробелов.<br> Проверки на достоверность НЕ будут проводиться! Если адаптер не работает после внесения изменений, проверьте введенные данные.<br> <b><u><i>ПРЕДУПРЕЖДЕНИЕ! Добавление точек данных для высокоприоритетного опроса может негативно повлиять на ваше устройство SENEC! Вы несете ответственность за побочные эффекты при использовании этого адаптера.</i></u></b>",
		"pt": "Aqui você pode alterar a prioridade de polling para pontos de dados específicos. Deixe os campos vazios para usar os valores padrão.<br> Para adicionar pontos de dados adicionais, insira-os separados por vírgulas, sem espaços em branco extras.<br> NENHUMA verificação de plausibilidade será feita! Se o adaptador não funcionar após suas alterações, verifique sua entrada.<br> <b><u><i>AVISO! Adicionar pontos de dados para pesquisa de alta prioridade pode afetar negativamente seu dispositivo SENEC! Os efeitos adversos são de sua responsabilidade ao usar este adaptador.</i></u></b>",
		"nl": "Hier kunt u de pollingprioriteit voor specifieke datapunten wijzigen. Laat velden leeg om standaardwaarden te gebruiken.<br> Om extra datapunten toe te voegen, voert u deze door komma's gescheiden in zonder extra spaties.<br> Er worden GEEN plausibiliteitscontroles uitgevoerd! Als de adapter niet werkt na uw wijzigingen, controleer dan uw invoer.<br> <b><u><i>WAARSCHUWING! Het toevoegen van datapunten voor polling met hoge prioriteit kan een negatief effect hebben op uw SENEC-apparaat! Nadelige effecten zijn uw verantwoordelijkheid bij het gebruik van deze adapter.</i></u></b>",
		"fr": "Ici, vous pouvez modifier la priorité d'interrogation pour des points de données spécifiques. Laissez les champs vides pour utiliser les valeurs par défaut.<br> Pour ajouter des points de données supplémentaires, saisissez-les séparés par des virgules sans aucun espace supplémentaire.<br> Il n'y aura AUCUN contrôle de plausibilité effectué ! Si l'adaptateur ne fonctionne pas après vos modifications, vérifiez votre entrée.<br> <b><u><i>ATTENTION! L'ajout de points de données pour l'interrogation à haute priorité peut affecter négativement votre appareil SENEC ! Les effets indésirables sont de votre responsabilité lors de l'utilisation de cet adaptateur.</i></u></b>",
		"it": "Qui è possibile modificare la priorità di polling per punti dati specifici. Lascia i campi vuoti per utilizzare i valori predefiniti.<br> Per aggiungere punti dati aggiuntivi, inseriscili separati da virgole senza spazi aggiuntivi.<br> NON verranno effettuati controlli di plausibilità! Se l'adattatore non funziona dopo le modifiche, controlla l'input.<br> <b><u><i>AVVERTIMENTO! L'aggiunta di punti dati per il polling ad alta priorità può influire negativamente sul tuo dispositivo SENEC! Gli effetti negativi sono responsabilità dell'utente quando si utilizza questo adattatore.</i></u></b>",
		"es": "Aquí puede cambiar la prioridad de sondeo para puntos de datos específicos. Deje los campos vacíos para usar los valores predeterminados.<br> Para agregar puntos de datos adicionales, introdúzcalos separados por comas sin espacios en blanco adicionales.<br> ¡NO se realizarán comprobaciones de plausibilidad! Si el adaptador no funciona después de sus cambios, verifique su entrada.<br> <b><u><i>¡ADVERTENCIA! ¡Agregar puntos de datos para el sondeo de alta prioridad puede afectar negativamente a su dispositivo SENEC! Los efectos adversos son su responsabilidad al utilizar este adaptador.</i></u></b>",
		"pl": "Tutaj możesz zmienić priorytet odpytywania dla określonych punktów danych. Aby użyć wartości domyślnych, pozostaw pola puste.<br> Aby dodać dodatkowe punkty danych, wprowadź je oddzielone przecinkami bez dodatkowych spacji.<br> NIE będą przeprowadzane żadne kontrole wiarygodności! Jeśli adapter nie działa po wprowadzeniu zmian, sprawdź dane wejściowe.<br> <b><u><i>OSTRZEŻENIE! Dodanie punktów danych do odpytywania o wysokim priorytecie może negatywnie wpłynąć na urządzenie SENEC! Niekorzystne skutki są Twoim obowiązkiem podczas korzystania z tego adaptera.</i></u></b>",
		"zh-cn": "您可以在此处更改特定数据点的轮询优先级。将字段留空以使用默认值。<br>要添加额外的数据点，请以逗号分隔输入它们，不要有任何额外的空格。<br>不会进行任何合理性检查！如果更改后适配器不起作用，请检查您的输入。<br><b><u><i>警告！为高优先级轮询添加数据点可能会对您的 SENEC 设备产生负面影响！使用此适配器时产生的不利影响是您的责任。</i></u></b>"
	},
	"statisticPrio": {
		"en": "STATISTIC High Prio Polling",
		"de": "STATISTIC High-Prio-Polling",
		"ru": "СТАТИСТИЧЕСКОЕ голосование с высоким приоритетом",
		"pt": "Sondagem STATISTIC de alto prêmio",
		"nl": "STATISTIC peiling met hoge prioriteit",
		"fr": "STATISTIC Sondage à priorité élevée",
		"it": "STATISTIC Sondaggio ad alta priorità",
		"es": "STATISTIC Encuesta de alto Prio",
		"pl": "STATISTIC Odpytywanie o wysokim priorytecie",
		"zh-cn": "统计高优先级轮询"
	},
	"statisticPrioTooltip": {
		"en": "Here you can add additional datapoints for STATISTIC High Priority Polling.<br>Default (when empty):<br>LIVE_GRID_EXPORT,LIVE_GRID_IMPORT,LIVE_HOUSE_CONS,LIVE_PV_GEN,LIVE_BAT_CHARGE_MASTER,LIVE_BAT_DISCHARGE_MASTER",
		"de": "Hier können Sie zusätzliche Datenpunkte für STATISTIC High Priority Polling hinzufügen.<br> Standard (wenn leer):<br> LIVE_GRID_EXPORT,LIVE_GRID_IMPORT,LIVE_HOUSE_CONS,LIVE_PV_GEN,LIVE_BAT_CHARGE_MASTER,LIVE_BAT_DISCHARGE_MASTER",
		"ru": "Здесь вы можете добавить дополнительные точки данных для СТАТИСТИЧЕСКОГО опроса с высоким приоритетом.<br> По умолчанию (когда пусто):<br> LIVE_GRID_EXPORT, LIVE_GRID_IMPORT, LIVE_HOUSE_CONS, LIVE_PV_GEN, LIVE_BAT_CHARGE_MASTER, LIVE_BAT_DISCHARGE_MASTER",
		"pt": "Aqui você pode adicionar pontos de dados adicionais para STATISTIC High Priority Polling.<br> Padrão (quando vazio):<br> LIVE_GRID_EXPORT, LIVE_GRID_IMPORT, LIVE_HOUSE_CONS, LIVE_PV_GEN, LIVE_BAT_CHARGE_MASTER, LIVE_BAT_DISCHARGE_MASTER",
		"nl": "Hier kunt u extra datapunten toevoegen voor STATISTISCHE peilingen met hoge prioriteit.<br> Standaard (indien leeg):<br> LIVE_GRID_EXPORT,LIVE_GRID_IMPORT,LIVE_HOUSE_CONS,LIVE_PV_GEN,LIVE_BAT_CHARGE_MASTER,LIVE_BAT_DISCHARGE_MASTER",
		"fr": "Ici, vous pouvez ajouter des points de données supplémentaires pour l'interrogation à haute priorité STATISTIC.<br> Par défaut (lorsque vide) :<br> LIVE_GRID_EXPORT,LIVE_GRID_IMPORT,LIVE_HOUSE_CONS,LIVE_PV_GEN,LIVE_BAT_CHARGE_MASTER,LIVE_BAT_DISCHARGE_MASTER",
		"it": "Qui puoi aggiungere punti dati aggiuntivi per STATISTIC High Priority Polling.<br> Predefinito (quando vuoto):<br> LIVE_GRID_EXPORT,LIVE_GRID_IMPORT,LIVE_HOUSE_CONS,LIVE_PV_GEN,LIVE_BAT_CHARGE_MASTER,LIVE_BAT_DISCHARGE_MASTER",
		"es": "Aquí puede agregar puntos de datos adicionales para STATISTIC High Priority Polling.<br> Por defecto (cuando está vacío):<br> LIVE_GRID_EXPORT, LIVE_GRID_IMPORT, LIVE_HOUSE_CONS, LIVE_PV_GEN, LIVE_BAT_CHARGE_MASTER, LIVE_BAT_DISCHARGE_MASTER",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla STATISTIC High Priority Polling.<br> Domyślnie (gdy pusty):<br> LIVE_GRID_EXPORT,LIVE_GRID_IMPORT,LIVE_HOUSE_CONS,LIVE_PV_GEN,LIVE_BAT_CHARGE_MASTER,LIVE_BAT_DISCHARGE_MASTER",
		"zh-cn": "您可以在此处为 STATISTIC 高优先级轮询添加其他数据点。<br>默认（空时）：<br> LIVE_GRID_EXPORT、LIVE_GRID_IMPORT、LIVE_HOUSE_CONS、LIVE_PV_GEN、LIVE_BAT_CHARGE_MASTER、LIVE_BAT_DISCHARGE_MASTER"
	},
	"energyPrio": {
		"en": "ENERGY High Prio Polling",
		"de": "ENERGY High-Prio-Polling",
		"ru": "Опрос ENERGY High Prio",
		"pt": "ENERGY High Prio Polling",
		"nl": "ENERGIE Hoge Prio Polling",
		"fr": "ÉNERGIE Sondage à priorité élevée",
		"it": "ENERGIA Sondaggio ad alta priorità",
		"es": "ENERGY High Prio Polling",
		"pl": "Odpytywanie o wysokim priorytecie ENERGIA",
		"zh-cn": "能源高优先级投票"
	},
	"energyPrioTooltip": {
		"en": "Here you can add additional datapoints for ENERGY High Priority Polling.<br>Default (when empty):<br>STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"de": "Hier können Sie zusätzliche Datenpunkte für ENERGY High Priority Polling hinzufügen.<br> Standard (wenn leer):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"ru": "Здесь вы можете добавить дополнительные точки данных для опроса с высоким приоритетом ENERGY.<br> По умолчанию (когда пусто):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"pt": "Aqui você pode adicionar pontos de dados adicionais para ENERGY High Priority Polling.<br> Padrão (quando vazio):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"nl": "Hier kunt u extra datapunten toevoegen voor ENERGY High Priority Polling.<br> Standaard (indien leeg):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"fr": "Ici, vous pouvez ajouter des points de données supplémentaires pour l'interrogation à haute priorité ENERGY.<br> Par défaut (lorsque vide) :<br> STAT_STATE,GUI_BAT_DATA_POWER,GUI_INVERTER_POWER,GUI_HOUSE_POW,GUI_GRID_POW,GUI_BAT_DATA_FUEL_CHARGE,GUI_CHARGING_INFO,GUI_BOOSTING_INFO,GUI_BAT_DATA_POWER_BATTAGE_BAT_DATA_FUEL_CHARGE,GUI_CHARGING_INFO,GUI_BOOSTING_INFO,GUI_BAT_DATA_POWER_BATTAGE_BAT_GUIDATA_VOLATA_BAT,GUI_BAT_GUIDATA_VOL.",
		"it": "Qui puoi aggiungere punti dati aggiuntivi per il polling ad alta priorità ENERGY.<br> Predefinito (quando vuoto):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"es": "Aquí puede agregar puntos de datos adicionales para ENERGY High Priority Polling.<br> Por defecto (cuando está vacío):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla odpytywania o wysokim priorytecie ENERGY.<br> Domyślnie (gdy pusty):<br> STAT_STATE, GUI_BAT_DATA_POWER, GUI_INVERTER_POWER, GUI_HOUSE_POW, GUI_GRID_POW, GUI_BAT_DATA_FUEL_CHARGE, GUI_CHARGING_INFO, GUI_BOOSTING_INFO, GUI_BAT_DATA_POWER, GUI_BAT_DATA_VOLTAGE, GUI_BAT_DATA_CURRENT, GUI_BAT_DATA_FUEL_CHARGE, GUI_BAT_DATA_OA_CHARGING, STAT_LIMITED_NET_SKEW",
		"zh-cn": "您可以在此处为 ENERGY 高优先级轮询添加其他数据点。<br>默认（空时）：<br> STAT_STATE,GUI_BAT_DATA_POWER,GUI_INVERTER_POWER,GUI_HOUSE_POW,GUI_GRID_POW,GUI_BAT_DATA_FUEL_CHARGE,GUI_CHARGING_INFO,GUI_BOOSTING_INFO,GUI_BAT_DATA_POWER,GUI_BAT_DATA_VOLTAGE,GUI_BAT_DATA_VOLTAGE,GUI_BAT_DATA_CURRENT_STATE_WGUI_BAT_DATA_CURRENT,FUEL_BAT_DATA_CURRENT,FULL"
	},
	"PV1Prio": {
		"en": "PV1 High Prio Polling",
		"de": "PV1 High-Prio-Polling",
		"ru": "PV1 High Prio Голосование",
		"pt": "Sondagem PV1 High Prio",
		"nl": "PV1 Polling met hoge prioriteit",
		"fr": "Sondage à priorité élevée PV1",
		"it": "Polling ad alta priorità PV1",
		"es": "Sondeo PV1 High Prio",
		"pl": "Odpytywanie o wysokim priorytecie PV1",
		"zh-cn": "PV1 高优先级轮询"
	},
	"PV1PrioTooltip": {
		"en": "Here you can add additional datapoints for PV1 High Priority Polling.<br>Default (when empty):<br>POWER_RATIO,MPP_POWER,MPP_INT",
		"de": "Hier können Sie zusätzliche Datenpunkte für PV1 High Priority Polling hinzufügen.<br> Standard (wenn leer):<br> POWER_RATIO,MPP_POWER,MPP_INT",
		"ru": "Здесь вы можете добавить дополнительные точки данных для высокоприоритетного опроса PV1.<br> По умолчанию (когда пусто):<br> МОЩНОСТЬ_RATIO, MPP_POWER, MPP_INT",
		"pt": "Aqui você pode adicionar pontos de dados adicionais para pesquisa de alta prioridade PV1.<br> Padrão (quando vazio):<br> POWER_RATIO, MPP_POWER, MPP_INT",
		"nl": "Hier kunt u extra datapunten toevoegen voor PV1 High Priority Polling.<br> Standaard (indien leeg):<br> POWER_RATIO,MPP_POWER,MPP_INT",
		"fr": "Ici, vous pouvez ajouter des points de données supplémentaires pour l'interrogation à haute priorité PV1.<br> Par défaut (lorsque vide) :<br> POWER_RATIO,MPP_POWER,MPP_INT",
		"it": "Qui è possibile aggiungere punti dati aggiuntivi per il polling ad alta priorità PV1.<br> Predefinito (quando vuoto):<br> POWER_RATIO,MPP_POWER,MPP_INT",
		"es": "Aquí puede agregar puntos de datos adicionales para el sondeo de alta prioridad PV1.<br> Por defecto (cuando está vacío):<br> POWER_RATIO, MPP_POWER, MPP_INT",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla odpytywania o wysokim priorytecie PV1.<br> Domyślnie (gdy pusty):<br> MOC_RATIO,MPP_POWER,MPP_INT",
		"zh-cn": "您可以在此处为 PV1 高优先级轮询添加其他数据点。<br>默认（空时）：<br>功率比，MPP_功率，MPP_INT"
	},
	"PWR_UNITPrio": {
		"en": "PWR_UNIT High Prio Polling",
		"de": "PWR_UNIT High-Prio-Polling",
		"ru": "PWR_UNIT Опрос с высоким приоритетом",
		"pt": "PWR_UNIT Sondagem de Prio Alto",
		"nl": "PWR_UNIT Polling met hoge prioriteit",
		"fr": "PWR_UNIT Interrogation à priorité élevée",
		"it": "PWR_UNIT Polling ad alta priorità",
		"es": "PWR_UNIT Sondeo de alto Prio",
		"pl": "PWR_UNIT Wysoki priorytet odpytywania",
		"zh-cn": "PWR_UNIT 高优先级轮询"
	},
	"PWR_UNITPrioTooltip": {
		"en": "Here you can add additional datapoints for PWR_UNIT High Priority Polling.<br>Default (when empty):<br>POWER_L1,POWER_L2,POWER_L3",
		"de": "Hier können Sie zusätzliche Datenpunkte für PWR_UNIT High Priority Polling hinzufügen.<br> Standard (wenn leer):<br> POWER_L1,POWER_L2,POWER_L3",
		"ru": "Здесь вы можете добавить дополнительные точки данных для высокоприоритетного опроса PWR_UNIT.<br> По умолчанию (когда пусто):<br> МОЩНОСТЬ_L1, МОЩНОСТЬ_L2, МОЩНОСТЬ_L3",
		"pt": "Aqui você pode adicionar pontos de dados adicionais para pesquisa de alta prioridade PWR_UNIT.<br> Padrão (quando vazio):<br> POWER_L1, POWER_L2, POWER_L3",
		"nl": "Hier kunt u extra datapunten toevoegen voor PWR_UNIT High Priority Polling.<br> Standaard (indien leeg):<br> POWER_L1,POWER_L2,POWER_L3",
		"fr": "Ici, vous pouvez ajouter des points de données supplémentaires pour l'interrogation à haute priorité PWR_UNIT.<br> Par défaut (lorsque vide) :<br> PUISSANCE_L1, PUISSANCE_L2, PUISSANCE_L3",
		"it": "Qui puoi aggiungere punti dati aggiuntivi per il polling ad alta priorità PWR_UNIT.<br> Predefinito (quando vuoto):<br> POTENZA_L1, POTENZA_L2, POTENZA_L3",
		"es": "Aquí puede agregar puntos de datos adicionales para el sondeo de alta prioridad PWR_UNIT.<br> Por defecto (cuando está vacío):<br> POWER_L1, POWER_L2, POWER_L3",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla odpytywania o wysokim priorytecie PWR_UNIT.<br> Domyślnie (gdy pusty):<br> MOC_L1, MOC_L2, MOC_L3",
		"zh-cn": "您可以在此处为 PWR_UNIT 高优先级轮询添加其他数据点。<br>默认（空时）：<br> POWER_L1,POWER_L2,POWER_L3"
	},
	"PM1OBJ1Prio": {
		"en": "PM1OBJ1 High Prio Polling",
		"de": "PM1OBJ1 High-Prio-Polling",
		"ru": "PM1OBJ1 High Prio Голосование",
		"pt": "PM1OBJ1 Sondagem de alto Prio",
		"nl": "PM1OBJ1 Opiniepeiling met hoge prioriteit",
		"fr": "PM1OBJ1 Sondage à priorité élevée",
		"it": "PM1OBJ1 Polling ad alta priorità",
		"es": "PM1OBJ1 Sondeo de alto Prio",
		"pl": "PM1OBJ1 Wysoki priorytet odpytywania",
		"zh-cn": "PM1OBJ1 高优先级轮询"
	},
	"PM1OBJ1PrioTooltip": {
		"en": "Here you can add additional datapoints for PM1OBJ1 High Priority Polling.<br>Default (when empty):<br>FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"de": "Hier können Sie zusätzliche Datenpunkte für PM1OBJ1 High Priority Polling hinzufügen.<br> Standard (wenn leer):<br> FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"ru": "Здесь вы можете добавить дополнительные точки данных для высокоприоритетного опроса PM1OBJ1.<br> По умолчанию (когда пусто):<br> FREQ, U_AC, I_AC, P_AC, P_TOTAL",
		"pt": "Aqui você pode adicionar pontos de dados adicionais para PM1OBJ1 de pesquisa de alta prioridade.<br> Padrão (quando vazio):<br> FREQ, U_AC, I_AC, P_AC, P_TOTAL",
		"nl": "Hier kunt u extra datapunten toevoegen voor PM1OBJ1 Polling met hoge prioriteit.<br> Standaard (indien leeg):<br> FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"fr": "Ici, vous pouvez ajouter des points de données supplémentaires pour l'interrogation à haute priorité PM1OBJ1.<br> Par défaut (lorsque vide) :<br> FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"it": "Qui è possibile aggiungere punti dati aggiuntivi per il polling ad alta priorità PM1OBJ1.<br> Predefinito (quando vuoto):<br> FREQ,U_AC,I_AC,P_AC,P_TOTALE",
		"es": "Aquí puede agregar puntos de datos adicionales para el sondeo de alta prioridad PM1OBJ1.<br> Por defecto (cuando está vacío):<br> FREQ, U_AC, I_AC, P_AC, P_TOTAL",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla PM1OBJ1 High Priority Polling.<br> Domyślnie (gdy pusty):<br> FREQ,U_AC,I_AC,P_AC,P_TOTALP",
		"zh-cn": "您可以在此处为 PM1OBJ1 高优先级轮询添加其他数据点。<br>默认（空时）：<br>频率，U_AC，I_AC，P_AC，P_TOTAL"
	},
	"PM1OBJ2Prio": {
		"en": "PM1OBJ2 High Prio Polling",
		"de": "PM1OBJ2 High-Prio-Polling",
		"ru": "PM1OBJ2 High Prio Голосование",
		"pt": "PM1OBJ2 Sondagem de alto Prio",
		"nl": "PM1OBJ2 Opiniepeiling met hoge prioriteit",
		"fr": "PM1OBJ2 Sondage à priorité élevée",
		"it": "PM1OBJ2 Polling ad alta priorità",
		"es": "PM1OBJ2 Sondeo de alto Prio",
		"pl": "PM1OBJ2 Wysoki priorytet odpytywania",
		"zh-cn": "PM1OBJ2 高优先级轮询"
	},
	"PM1OBJ2PrioTooltip": {
		"en": "Here you can add additional datapoints for PM1OBJ2 High Priority Polling.<br>Default (when empty):<br>FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"de": "Hier können Sie zusätzliche Datenpunkte für PM1OBJ2 High Priority Polling hinzufügen.<br> Standard (wenn leer):<br> FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"ru": "Здесь вы можете добавить дополнительные точки данных для высокоприоритетного опроса PM1OBJ2.<br> По умолчанию (когда пусто):<br> FREQ, U_AC, I_AC, P_AC, P_TOTAL",
		"pt": "Aqui você pode adicionar pontos de dados adicionais para PM1OBJ2 de pesquisa de alta prioridade.<br> Padrão (quando vazio):<br> FREQ, U_AC, I_AC, P_AC, P_TOTAL",
		"nl": "Hier kunt u extra datapunten toevoegen voor PM1OBJ2 Polling met hoge prioriteit.<br> Standaard (indien leeg):<br> FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"fr": "Ici, vous pouvez ajouter des points de données supplémentaires pour l'interrogation à haute priorité PM1OBJ2.<br> Par défaut (lorsque vide) :<br> FREQ,U_AC,I_AC,P_AC,P_TOTAL",
		"it": "Qui è possibile aggiungere punti dati aggiuntivi per il polling ad alta priorità PM1OBJ2.<br> Predefinito (quando vuoto):<br> FREQ,U_AC,I_AC,P_AC,P_TOTALE",
		"es": "Aquí puede agregar puntos de datos adicionales para el sondeo de alta prioridad PM1OBJ2.<br> Por defecto (cuando está vacío):<br> FREQ, U_AC, I_AC, P_AC, P_TOTAL",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla PM1OBJ2 High Priority Polling.<br> Domyślnie (gdy pusty):<br> FREQ,U_AC,I_AC,P_AC,P_TOTALP",
		"zh-cn": "您可以在此处为 PM1OBJ2 高优先级轮询添加其他数据点。<br>默认（空时）：<br>频率，U_AC，I_AC，P_AC，P_TOTAL"
	},
	"Polling priority": {
		"en": "Polling priority",
		"de": "Abrufpriorität",
		"ru": "Приоритет опроса",
		"pt": "Prioridade de votação",
		"nl": "Polling prioriteit",
		"fr": "Priorité d'interrogation",
		"it": "Priorità di votazione",
		"es": "Prioridad de sondeo",
		"pl": "Priorytet odpytywania",
		"zh-cn": "轮询优先级"
	},
	"extraPrio": {
		"en": "Additional High Prio Polling",
		"de": "Zusätzliche High-Prio-Abfrage",
		"ru": "Дополнительный опрос с высоким приоритетом",
		"pt": "Sondagem Adicional de Alto Prio",
		"nl": "Extra polling met hoge prioriteit",
		"fr": "Sondage à priorité élevée supplémentaire",
		"it": "Polling ad alta priorità aggiuntivo Additional",
		"es": "Sondeo adicional de alto Prio",
		"pl": "Dodatkowe odpytywanie o wysokim priorytecie",
		"zh-cn": "额外的高优先级轮询"
	},
	"extraPrioTooltip": {
		"en": "You may add additional datapoints for high priority polling here.<br>Do NOT add datapoints from categories above here!<br>There will be NO syntax checking. If adapter breaks, check your input!<br>Datapoints need to be added <b>EXACTLY</b> like this:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"de": "Sie können hier zusätzliche Datenpunkte für Abfragen mit hoher Priorität hinzufügen.<br> Fügen Sie hier KEINE Datenpunkte aus den obigen Kategorien hinzu!<br> Es findet KEINE Syntaxprüfung statt. Falls der Adapter Probleme hat, überprüfen Sie Ihre Eingabe!<br> Datenpunkte müssen <b>GENAU</b> wie folgt hinzugefügt werden:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"ru": "Здесь вы можете добавить дополнительные точки данных для высокоприоритетного опроса.<br> НЕ добавляйте сюда точки данных из категорий выше!<br> Никакой проверки синтаксиса не будет. Если адаптер сломается, проверьте свой ввод!<br> Datapoints нужно добавлять <b>ТОЧНО</b> так:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"pt": "Você pode adicionar pontos de dados adicionais para pesquisa de alta prioridade aqui.<br> NÃO adicione pontos de dados das categorias acima aqui!<br> NÃO haverá verificação de sintaxe. Se o adaptador quebrar, verifique sua entrada!<br> Os pontos de dados precisam ser adicionados <b>EXATAMENTE</b> assim:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"nl": "U kunt hier extra datapunten toevoegen voor polling met hoge prioriteit.<br> Voeg hier GEEN datapunten uit bovenstaande categorieën toe!<br> Er vindt GEEN syntaxiscontrole plaats. Als de adapter kapot gaat, controleer dan uw invoer!<br> Datapunten moeten <b>PRECIES</b> als volgt worden toegevoegd:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"fr": "Vous pouvez ajouter ici des points de données supplémentaires pour une interrogation de haute priorité.<br> N'ajoutez PAS de points de données des catégories ci-dessus ici !<br> Il n'y aura AUCUNE vérification de syntaxe. Si l'adaptateur se casse, vérifiez votre entrée !<br> Les points de données doivent être ajoutés <b>EXACTEMENT</b> comme ceci :<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"it": "È possibile aggiungere ulteriori punti dati per il polling ad alta priorità qui.<br> NON aggiungere punti dati dalle categorie sopra qui!<br> Non ci sarà NESSUN controllo della sintassi. Se l'adattatore si rompe, controlla il tuo input!<br> I punti dati devono essere aggiunti <b>ESATTAMENTE in</b> questo modo:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"es": "Puede agregar puntos de datos adicionales para el sondeo de alta prioridad aquí.<br> ¡NO agregue puntos de datos de las categorías anteriores aquí!<br> NO habrá verificación de sintaxis. Si el adaptador se rompe, verifique su entrada.<br> Los puntos de datos deben agregarse <b>EXACTAMENTE</b> así:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"pl": "Tutaj możesz dodać dodatkowe punkty danych dla odpytywania o wysokim priorytecie.<br> NIE dodawaj tutaj punktów danych z powyższych kategorii!<br> Nie będzie sprawdzania składni. Jeśli adapter się zepsuje, sprawdź dane wejściowe!<br> Punkty danych należy dodać <b>DOKŁADNIE w</b> ten sposób:<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}",
		"zh-cn": "您可以在此处为高优先级轮询添加其他数据点。<br>不要在此处添加来自上述类别的数据点！<br>将没有语法检查。如果适配器损坏，请检查您的输入！<br>数据点需要<b>准确地</b>添加这样的：<br>\"CATEGORY1\":{\"DP1\":\"\",\"DP2\":\"\"},\"CATEGORY2\":{\"DP3\":\"\",\"DP4\":\"\"}"
	}
};
